### ISSUE TITLE
[$20] Handle colors are incorrect when users are tagged in posts

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#145] opened 2020-11-10 03:58 UTC
**Steps**
Go to the forums as any user (link - https://vanilla.topcoder-dev.com/)
Add a comment or edit a discussion or add a new thread
Tag any user in the post

**Actual result**
Handle colors are incorrect when users are tagged in posts

![image](https://user-images.githubusercontent.com/4592712/98626092-f2952980-2336-11eb-96e8-9c2f74a4c05d.png)

**Comment by jmgasper** [comment] 2020-11-10 08:12
Contest https://www.topcoder.com/challenges/30149977 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-10 08:13
@sdgun - I can't reproduce this.  Can you provide more details please?

![Screen Shot 2020-11-10 at 19 13 11](https://user-images.githubusercontent.com/21790/98647304-c73b2a80-2388-11eb-84eb-2fd4dd8f2273.png)

**Comment by sdgun** [comment] 2020-11-10 08:52
@jmgasper Please check this video

[Handles.zip](https://github.com/topcoder-platform/forums/files/5516005/Handles.zip)

**Comment by jmgasper** [comment] 2020-11-10 09:05
@sdgun - Can you try logging in with TonyJ please?  I'm interested to see if that makes a difference.  Your example renders alright for me:

![Screen Shot 2020-11-10 at 20 04 25](https://user-images.githubusercontent.com/21790/98652644-10db4380-2390-11eb-8855-e167e2c1fde9.png)

**Comment by sdgun** [comment] 2020-11-10 09:34
@jmgasper I still see the same behavior 

[Handles from tonyj.zip](https://github.com/topcoder-platform/forums/files/5516227/Handles.from.tonyj.zip)

**Comment by jmgasper** [comment] 2020-11-10 09:36
@sdgun - What browser?

**Comment by sdgun** [comment] 2020-11-10 09:39
Chrome Version 86.0.4240.183, but I see this behavior in Firefox too

**Comment by jmgasper** [comment] 2020-11-10 22:00
Contest https://www.topcoder.com/challenges/30149977 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-10 22:00
@atelomycterus - I can't seem to reproduce this.  Any thoughts on your side?

**Comment by atelomycterus** [comment] 2020-11-11 06:45
@jmgasper 
> I can't seem to reproduce this. Any thoughts on your side?
I can't reproduce it. 

@sdgun Please clear browser cache.  `chrome://settings/clearBrowserData`
![image](https://user-images.githubusercontent.com/10196632/98777361-a06d0a80-2401-11eb-8366-9acfb03f6961.png)

Chrome:
![image](https://user-images.githubusercontent.com/10196632/98777727-4fa9e180-2402-11eb-99b5-38e53a537bb3.png)

![image](https://user-images.githubusercontent.com/10196632/98777044-191f9700-2401-11eb-90c2-1ad8a004bb8c.png)

Opera:
![image](https://user-images.githubusercontent.com/10196632/98777946-aa433d80-2402-11eb-812e-41ae97e401c7.png)

**Comment by sdgun** [comment] 2020-11-11 07:05
@jmgasper Worked after clearing cache

**Comment by jmgasper** [comment] 2020-11-12 06:38
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30149977<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2020-11-12 06:38 UTC
Labels: Dev env, P2, QAverified, bug, tcx_Assigned, tcx_FixAccepted
