### ISSUE TITLE
[$25] Category drop down shows blank rows in the challenges created from Vanilla

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#219] opened 2020-11-20 07:47 UTC
**Steps**
Log in as Tonyj
Go to https://vanilla.topcoder-dev.com/groups?filter=challenge
Click Challenge button
Create a new challenge
As the same user or as a normal user log into forum >> access above created challenge
In the newly created challenge click New Announcement or New Discussion buttons
Click category drop down >> close it and click it again

Category drop down shows blank rows

Ex challenge - https://vanilla.topcoder-dev.com/group/186

![image](https://user-images.githubusercontent.com/4592712/99773584-aade8100-2b32-11eb-9372-0f8ab5dd09d6.png)

**Comment by jmgasper** [comment] 2020-11-29 02:13
Contest https://www.topcoder.com/challenges/30154454 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-29 02:15
Contest https://www.topcoder.com/challenges/30154454 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2020-11-30 18:23
@sdgun 
1. Challenge only can be created by a challenge forum processor.  'Challenge' button has been hidden (issue - https://github.com/topcoder-platform/forums/issues/218)

2. I see you tested with Firefox.  I couldn't reproduce it. I've tested it using Chrome/Opera/Firefox.  
What version of Firefox?  Could you record a video? Thanks!
Firefox:
![image](https://user-images.githubusercontent.com/10196632/100648081-7ef0a600-3351-11eb-975c-511b11aebf61.png)

**Comment by sdgun** [comment] 2020-12-01 04:29
@atelomycterus This issue only occurred for manually created challenges which is now removed in [#218 ](https://github.com/topcoder-platform/forums/issues/218)

**Comment by jmgasper** [comment] 2020-12-01 04:56
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30154454<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2020-12-01 04:56 UTC
Labels: Dev env, P2, QAverified, bug, tcx_Assigned, tcx_Feedback, tcx_FixAccepted

**Comment by sdgun** [comment] 2020-12-04 05:22
@atelomycterus @jmgasper Looks like my above comment is incorrect, I can see this happening in Firefox again, version is 83.0.

**Steps**
Go to https://vanilla.topcoder-dev.com
Click New Discussion
Click Category drop down(Even the challenge names and categories have no visual difference)
Select any category
Click Category drop down again

[Screencast 2020-12-04.zip](https://github.com/topcoder-platform/forums/files/5640745/Screencast.2020-12-04.zip)
