### ISSUE TITLE
[$300] Update UI: Watching feature

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/forums#577] opened 2021-04-15 17:25 UTC
Expected behavior: 
**PUBLIC FORUMS** 
1) If user is "watching" a parents category, the eye ball should be turned on for all sub-threads in that parents category
2) If user turns off the "watch" feature on any sub-thread, the eyeball icon should be turned off on the parent category
3) Add "watch" eyeball icon on the parent level next to title. See screenshot below

**Comment by hokienick** [comment] 2021-04-15 17:33
![Sub-eyeball](https://user-images.githubusercontent.com/1373998/114913383-fc372780-9dd5-11eb-9bee-390242b1b876.png)

**Comment by jmgasper** [comment] 2021-04-15 23:55
@atelomycterus - Please see above and let me know your thoughts

My initial concerns relayed to the team were:

The problem is that, if a user has a watch on the main category, they do not have watches on each individual thread - that's implicit.
So, if the user un-watches a thread, we have to:

- Unwatch the category
- Watch every thread explicitly
- Remove the watch for the single thread that was unclicked

And, if the user chooses to watch the whole category again, we have to:

- Unwatch every thread
- Add the watch to the category

Not a big deal, but I just wanted to point out that this is a little more complex than it may appear on the surface. 

The other side effect that we have to think about is what happens if a user turns the watch off for a parent category and a new thread is added?  Do we watch that thread by default or no?

**Comment by jmgasper** [comment] 2021-04-19 23:16
Challenge https://www.topcoder.com/challenges/eac0097e-cb13-4b16-9b5f-fc115c5fcec0 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2021-04-19 23:17
@atelomycterus - Any thoughts on this one?  Is there any way we can have a category level watch but ignore specific discussions underneath that category watch?

**Comment by jmgasper** [comment] 2021-04-19 23:17
Challenge https://www.topcoder.com/challenges/eac0097e-cb13-4b16-9b5f-fc115c5fcec0 has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2021-04-20 05:44
@jmgasper I keep in mind, but did not want to rush to this task.

From the screen above User is watching `New Here & Getting Started` category. 

### DB
Watching a category: data are stored in UserMeta table. 4 records should be inserted per a watched category:
```
Preferences.Email.NewComment.CATEGORY_ID
Preferences.Email.NewDiscussion.CATEGORY_ID
Preferences.Popup.NewComment.CATEGORY_ID
Preferences.Popup.NewDiscussion.CATEGORY_ID
```

### Watching a category (`discussions` type) 
Example, User is watching `New Here & Getting Started` category.

> 1. If user is "watching" a parents category, the eye ball should be turned on for all sub-threads in that parents category

Ok, we can show the green eye ball.

> 2. If user turns off the "watch" feature on any sub-thread, the eyeball icon should be turned off on the parent category

- _Unwatch the category_
Yes, remove data from UserMeta table.

- _Watch every thread explicitly_
- _Remove the watch for the single thread that was unclicked_

Yes, need to get all discussion IDs in CategoryID except unclicked discussionID and insert XXX records with Bookmaked flag (1) in UserDiscusssion table.



> And, if the user chooses to watch the whole category again, we have to:

- _Unwatch every thread_
For consistency, it'd better to set `Bookmarked flag = 0` for all discsussion with this categoryID in UserDiscussion table. 
- _Add the watch to the category_
Yes, insert data into UserMeta table.

> The other side effect that we have to think about is what happens if a user turns the watch off for a parent category and a new thread is added? 
Do we watch that thread by default or no?

No notifications if a new thread is added or a new comment is added for previously created threads. 

I think a small change will help simplify it and we can meet the requirements.

1. If user is "watching" a parents category, the eye ball should be turned on for all sub-threads in that parents category.

2. If user turns off the "watch" feature on any sub-thread, the eyeball icon **IS NOT** changed on the parent category. 
We don't remove data from UserMeta table. So user can receive notifications if a new thread is added or new comment is added for other threads.
  
Show the **grey** eye ball icon for an unwatched sub-thread only. 

We add only one record in UserDiscussion with `Bookmaked flag = 0`. Bookmaked column has existed in UserDiscussion. 
So we don't need to insert a bunch of new records in UserDiscussion. 

Need to fix  Vanilla notifications if user watches a category and new comments are added to unwatched thread then don't send any notifications. 

If user turns on the "watch" feature on this sub-thread again. We need to update `Bookmaked flag = 1`. 

> 3.Add "watch" eyeball icon on the parent level next to title. See screenshot below

Ok

###  Watching a category (`nested` type)
Example,  Watching `General` category, the parent of `New Here & Getting Started` category
It's more complicated case. Let's me know if this is in the scope.

**Comment by jmgasper** [comment] 2021-04-20 06:33
@atelomycterus - This is great information, thanks, and in-line with what I was hoping we'd be able to do.  Let's skip watching the root category, like `General` for now - we can figure that out later.

**Comment by atelomycterus** [comment] 2021-04-20 20:33
@jmgasper Please apply PRs:
- https://github.com/topcoder-platform/forums/pull/590
- https://github.com/topcoder-platform/forums-theme/pull/46/

Thanks!


### Testing
Please clear browser cache before testing. Let me know if you have any questions.

![image](https://user-images.githubusercontent.com/10196632/115459922-497d2400-a230-11eb-92da-b08c457c264d.png)


![image](https://user-images.githubusercontent.com/10196632/115459887-3c603500-a230-11eb-911b-639dfa91b977.png)

**Comment by jmgasper** [comment] 2021-04-20 23:03
@atelomycterus - This looks really good to me, thanks!  I'm just getting feedback from Topcoder as well.

**Comment by jmgasper** [comment] 2021-04-21 00:29
@atelomycterus - One clarification from Topcoder:

If a user is watching a category and turns "off" the watch on a discussion underneath that category, Topcoder would like the category watch to be turned off.

**Comment by atelomycterus** [comment] 2021-04-21 10:57
@jmgasper  
> If a user is watching a category and turns "off" the watch on a discussion underneath that category, Topcoder would like the category watch to be turned off.

Fixed. 

### Testing
Please correct me if i am wrong. This is implemented only for Public Forums.
action | results
-- | --
watch a category (grey + init state: default, it means user hasn't clicked on watching/unwatching a discussion) | category - green , all discussions - green, email notifications (new discussions/comments)
category(green) , unwatch it | category - gray , discussions - gray, no notifications

action | results
-- | --
watch another category (grey+init state: default) | category - green , discussions - green, get email notifications (comments+new discussions)
unwatch a discussion in this category | category - grey,  unwatched discussion - grey, other discussions without changes,  get email notifications (new discussions + new comments for discussions  with green icons), no email notifications about new comments for  the unwatched discussion
new discussion added by an user | new discussion with the green icon +  get email notifications about new  comments
unwatch this discussion | no email notifications about new  comments for this discussion
a category (green), unwatch it | no email notificatins for new discussions/comments, discussions unwatched/watched manually - no changes,  other discussions - grey icons
a category (grey, but has been watched earlier), watch again | email notificatins for new discussions/comments, discussions unwatched/watched manually - no changes,  other discussions - green icons







Please apply PRs:

https://github.com/topcoder-platform/forums-groups-plugin/pull/85
https://github.com/topcoder-platform/forums/pull/591

Thanks!

**Comment by jmgasper** [comment] 2021-04-21 12:01
@atelomycterus - Looks good, thanks.  I'm going to close this out now and will take any additional feedback from Topcoder as new tickets.

**Comment by jmgasper** [comment] 2021-04-21 12:01
Payment task has been updated: https://www.topcoder.com/challenges/eac0097e-cb13-4b16-9b5f-fc115c5fcec0
*Payments Complete*
Winner: obog
Copilot: ghostar
Challenge `eac0097e-cb13-4b16-9b5f-fc115c5fcec0` has been paid and closed.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2021-04-21 12:01 UTC
Labels: March 2021 Shapeup, tcx_Assigned, tcx_FixAccepted, tcx_ReadyForReview
