### ISSUE TITLE
[$25] Smiles are always shown in a new line in the notification

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#245] opened 2020-11-30 03:22 UTC
**Steps**
Log in as any user and go to any discussion
Add a comment/reply or a new discussion with some smileys
Check the email notification by logging in from another user who is watching the discussion

Smiles are always shown in a new line in the notification

Forum:
![image](https://user-images.githubusercontent.com/4592712/100565328-546b0280-32e9-11eb-8d74-81136381e11e.png)

Email:
![image](https://user-images.githubusercontent.com/4592712/100565339-5b921080-32e9-11eb-8cea-1fd6a7c34807.png)

**Comment by jmgasper** [comment] 2020-11-30 05:18
Contest https://www.topcoder.com/challenges/30154494 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-30 05:18
Contest https://www.topcoder.com/challenges/30154494 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2020-11-30 10:29
@jmgasper @sdgun Couldn't reproduce it. Tested with 2 different web clients and mobile.  
@sdgun What mail client do you use? Could you forward me (o_bogdanova@inbox.ru) your email? I'll have a look at view source. 

Testing:
https://vanilla.topcoder-dev.com/discussion/1869/tco-2020-test-with-smiles
https://vanilla.topcoder-dev.com/discussion/1740/tests-handles#latest


![image](https://user-images.githubusercontent.com/10196632/100597773-e33e4600-330e-11eb-9dcc-51be9b3c199f.png)

![image](https://user-images.githubusercontent.com/10196632/100597739-da4d7480-330e-11eb-82e7-bd684ace751c.png)

![image](https://user-images.githubusercontent.com/10196632/100597904-0ff25d80-330f-11eb-9da4-8eee885c6c9a.png)
![image](https://user-images.githubusercontent.com/10196632/100598246-868f5b00-330f-11eb-84fe-8a0d245b0014.png)

**Comment by sdgun** [comment] 2020-11-30 10:50
@atelomycterus Attachments for your reference, please let me know if you need any more information

[Smiley issue 2.zip](https://github.com/topcoder-platform/forums/files/5615480/Smiley.issue.2.zip)
[Smiley issue.zip](https://github.com/topcoder-platform/forums/files/5615481/Smiley.issue.zip)

**Comment by atelomycterus** [comment] 2020-11-30 15:29
@sdgun Thanks! 
@jmgasper Let me know what should be fixed/implemented.

1) To support text emoticons  (`:)` , and so on) - need to write a custom blot (aka extension for Rich Editor)

2) Tested with Gmail. It replaces smiles with own images. 
![image](https://user-images.githubusercontent.com/10196632/100629039-e8fd5100-3339-11eb-82c2-5d6021c48e57.png)


![image](https://user-images.githubusercontent.com/10196632/100627845-94a5a180-3338-11eb-9d34-cc3b61a09ca4.png)

The original content:
![image](https://user-images.githubusercontent.com/10196632/100628060-dafb0080-3338-11eb-9e1c-cc026d5b7153.png)

**Comment by jmgasper** [comment] 2020-11-30 20:42
@atelomycterus - I don't think we want to do a bunch of custom work for this.  I'm going to close this for now and we can revisit it way in the future if it's still an issue.

**Comment by jmgasper** [comment] 2020-11-30 20:42
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30154494<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed by jmgasper** 2020-11-30 20:42 UTC
Labels: Dev env, P2, bug, tcx_Assigned, tcx_Feedback, tcx_FixAccepted
