### ISSUE TITLE
[$25] When click unfollow, the category is removed

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#211] opened 2020-11-19 16:18 UTC
**Steps**
Go to a development challenge forum as any user
Click Unfollow on any available category

The category is removed. But we have to keep the category and only remove it from the 'following' categories list

[Screencast 2020-11-19.zip](https://github.com/topcoder-platform/forums/files/5568163/Screencast.2020-11-19.zip)

**Comment by jmgasper** [comment] 2020-11-19 22:49
Contest https://www.topcoder.com/challenges/30152326 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-19 22:49
Contest https://www.topcoder.com/challenges/30152326 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2020-11-20 05:40
The same issue - CategoryTree is empty. Related issues - https://github.com/topcoder-platform/forums/issues/194

**Comment by atelomycterus** [comment] 2020-11-20 16:42
@sdgun @jmgasper I've looked through Vanilla code.
User can't see categories due to 'Followed' (true) flag.  By default the filter view is always displayed in Recent Discussions page or '/categories' (no category selected).   After setting 'following' Vanilla saves user preferences and doesn't display the view filter for a category page and shows only following categories.  So if the category has nested categories they don't are displayed. It's confusing.
I've set `enableFollowingFilter = true;` and the view filter is always displayed for a category .  
![image](https://user-images.githubusercontent.com/10196632/99823520-8c45ad80-2b65-11eb-947c-1d5a12609d4e.png)

![image](https://user-images.githubusercontent.com/10196632/99823558-98316f80-2b65-11eb-9427-c111fab5eeb4.png)

I've noticed that View filter does a postback, so you can see unexpected behavior like redirecting to 'All categories'. I haven't fixed it because I don't know if you want to keep the view filter in a page.

The postbacks and redirecting to 'all categories':
  
![image](https://user-images.githubusercontent.com/10196632/99825343-f7907f00-2b67-11eb-873b-8adab06773a2.png)


Another option -  fix Category Controller and  don't use Followed flag in Category Controller, display all categories (/categories/XXXX). Use the filter view only in Recent Discussions and 'All categories' page (/categories):
![image](https://user-images.githubusercontent.com/10196632/99825555-3a525700-2b68-11eb-8e9a-109a15c9ecc6.png)


So let me know your feedback.

**Comment by jmgasper** [comment] 2020-11-21 06:16
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30152326<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2020-11-21 06:15 UTC
Labels: Dev env, P1, bug, tcx_Assigned, tcx_FixAccepted

**Comment by sdgun** [comment] 2020-11-23 06:48
@jmgasper When copilot clicks on 'Following' from view drop down it is redirecting to ALL CATEGORIES as @atelomycterus has mentioned  in his comment above. But then if the user clicks browser back button or access the challenge discussion from challenge details page it is not showing any categories to the user

[Copilot.zip](https://github.com/topcoder-platform/forums/files/5581362/Copilot.zip)

**Comment by atelomycterus** [comment] 2020-11-23 06:55
@sdgun @jmgasper The duplicate issue https://github.com/topcoder-platform/forums/issues/226 . The bug in 'FollowingCategoryModule', I see in the your video a wrong url generated
