### ISSUE TITLE
[$150] Updated UI: Popups

### ISSUE THREAD

**Issue by atelomycterus** [topcoder-platform/forums#559] opened 2021-04-09 06:08 UTC
@jmgasper The popup window in MarvelApp:
Screen https://marvelapp.com/prototype/c06bg41/screen/77911788
![image](https://user-images.githubusercontent.com/10196632/114136073-d1029300-9912-11eb-9b5d-c307f7de8397.png)

The current design:
![image](https://user-images.githubusercontent.com/10196632/114136320-2e96df80-9913-11eb-80ed-1c0007babde9.png)

**Comment by jmgasper** [comment] 2021-04-09 06:25
Challenge https://www.topcoder.com/challenges/06cb08ac-24da-4060-94cd-f3645850ec58 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2021-04-09 06:25
Challenge https://www.topcoder.com/challenges/06cb08ac-24da-4060-94cd-f3645850ec58 has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2021-04-16 17:13
@jmgasper At least 7 popups should be fixed. Each popup is  a separate view with a different title and message. 
1. Should I update only UI ? 
2. Does this requirement include updating titles/messages? For example, the `Delete Discussion` title should be changed to `Delete` ( `Add a new Category`  =>  `Add`, `Invite User` => `Invite`). 
For example, the `Are you sure you want to delete this discussion?` message should be changed to `Are you sure you want to delete this item?`

### Discussion page
 - Announce 
 
![image](https://user-images.githubusercontent.com/10196632/115058982-8ecaea00-9eee-11eb-92f7-da82bd21982a.png)

 - Move a discussion
 
![image](https://user-images.githubusercontent.com/10196632/115058269-c38a7180-9eed-11eb-80bb-27bed0e5555e.png)

 - Delete a discussion
![image](https://user-images.githubusercontent.com/10196632/115058298-cd13d980-9eed-11eb-8ed6-3a5244fd1a49.png)


### Group page
 - Add New Category
 
![image](https://user-images.githubusercontent.com/10196632/115058194-a655a300-9eed-11eb-8f9e-7251f4b41c91.png)

 - Delete a group
 
![image](https://user-images.githubusercontent.com/10196632/115058111-8aea9800-9eed-11eb-8f75-bdf533ec4f8c.png)

 - Invite member
![image](https://user-images.githubusercontent.com/10196632/115058141-9342d300-9eed-11eb-971a-16bb15cb4054.png)

 
### Profile page

![image](https://user-images.githubusercontent.com/10196632/115059116-c6399680-9eee-11eb-9855-6711af66afed.png)

**Comment by jmgasper** [comment] 2021-04-17 03:28
@atelomycterus - I bumped the payment here.  Yeah, let's try to get as close to the MarvelApp as possible, thanks!

**Comment by atelomycterus** [comment] 2021-04-17 20:24
@jmgasper Please apply PRs:
- https://github.com/topcoder-platform/forums-theme/pull/42
- https://github.com/topcoder-platform/forums-groups-plugin/pull/82
- https://github.com/topcoder-platform/forums/pull/583
Thanks!

### Testing
Please clear browser cache before testing,
I've fixed all mentioned popups. Let me know if I missed any popups.
Delete popup looks the same for group / discussion/ token. 

![image](https://user-images.githubusercontent.com/10196632/115125620-0de51e80-9fd2-11eb-9599-ae848c98d7cf.png)

Other popups:
![image](https://user-images.githubusercontent.com/10196632/115125795-34f02000-9fd3-11eb-978c-f9ac35493c58.png)

**Comment by sdgun** [comment] 2021-04-18 00:18
@atelomycterus Even after clearing cache, I don't see any of these pop ups.

**Comment by jmgasper** [comment] 2021-04-18 00:32
@sdgun - I can see them.  Tested delete, move, announce

<img width="1530" alt="Screen Shot 2021-04-18 at 10 31 19 am" src="https://user-images.githubusercontent.com/21790/115130247-5f70c600-a031-11eb-838b-1b168d32c967.png">

**Comment by jmgasper** [comment] 2021-04-18 00:32
Payment task has been updated: https://www.topcoder.com/challenges/06cb08ac-24da-4060-94cd-f3645850ec58
*Payments Complete*
Winner: obog
Copilot: ghostar
Challenge `06cb08ac-24da-4060-94cd-f3645850ec58` has been paid and closed.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2021-04-18 00:32 UTC
Labels: March 2021 Shapeup, Ready for QA, tcx_Assigned, tcx_FixAccepted

**Comment by sdgun** [comment] 2021-04-18 01:06
@atelomycterus Verified in Dev. 

1. Delete comment pop up is not implemented as per the design, also after deleting a comment, the pop up is not getting closed and the screen shows a weird layout.

![image](https://user-images.githubusercontent.com/4592712/115130524-093e5b80-a00e-11eb-8ebd-3b3b285a20e7.png)

https://user-images.githubusercontent.com/4592712/115130627-cdf05c80-a00e-11eb-8061-3942a0befef0.mp4

2. I don't see the Move option for copilot or admin anymore

Delete discussion is working as expected:
![image](https://user-images.githubusercontent.com/4592712/115130511-faf03f80-a00d-11eb-90b5-4f059c465ddb.png)

Announce is as expected:
![image](https://user-images.githubusercontent.com/4592712/115130647-f415fc80-a00e-11eb-9ed2-e5a4c302e330.png)

Delete group:
![image](https://user-images.githubusercontent.com/4592712/115130719-730b3500-a00f-11eb-9b72-0ccd4cbe292e.png)

Invite users:
![image](https://user-images.githubusercontent.com/4592712/115130736-90d89a00-a00f-11eb-9826-8bf9f2a6cd2a.png)

Add category:
![image](https://user-images.githubusercontent.com/4592712/115130762-d301db80-a00f-11eb-897b-ce490c82d374.png)

**Comment by jmgasper** [comment] 2021-04-18 01:10
@sdgun - I see `Move` as an option for TonyJ:

<img width="995" alt="Screen Shot 2021-04-18 at 11 09 45 am" src="https://user-images.githubusercontent.com/21790/115130878-9dbcb400-a036-11eb-9eab-07109b0a56c7.png">

<img width="956" alt="Screen Shot 2021-04-18 at 11 09 35 am" src="https://user-images.githubusercontent.com/21790/115130881-9f867780-a036-11eb-8653-8b5a52ea3085.png">

**Comment by jmgasper** [comment] 2021-04-18 01:10
I also can't reproduce the `Delete` issue - it's working fine for me.

**Comment by sdgun** [comment] 2021-04-18 01:32
Created new issue for comment deleting related issues : https://github.com/topcoder-platform/forums/issues/584

**Comment by sdgun** [comment] 2021-04-18 02:00
Verified the below in production.

Deleting a comment
Move
Deleting a thread
Announcements

**Comment by atelomycterus** [comment] 2021-04-18 11:33
@sdgun @jmgasper Please apply PR-https://github.com/topcoder-platform/forums/pull/586. Thanks!

1. >  Delete comment pop up is not implemented as per the design, also after deleting a comment, 

I missed it. The 'Deleting a comment' popup is generated with jquery.popup.js, other popups are implemented with php views.
Sorry about that. I've fixed:

![image](https://user-images.githubusercontent.com/10196632/115142699-d0bd7280-a04b-11eb-8c41-808c6985a6d2.png)

2. > I don't see the Move option for copilot or admin anymore

We've removed Edit permission (https://github.com/topcoder-platform/forums/issues/490#issuecomment-806382278). Moving  a discussion requires:
 - Discussion.Edit permission 
 - Discussion.Add permission on the target category.
