### ISSUE TITLE
[$100] Prod - Active Gig Workers

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/forums#631] opened 2021-06-04 21:55 UTC
@atelomycterus - Topcoder admins are saying that they aren't adding folks to the `Active Gig Workers` group, but it's still growing at a rapid rate.  This was a custom role we added - it's not synced from the Topcoder side (group type = `member`, not `Topcoder`).  Are there any reasons why folks may be getting automatically added to that group?  Any way we can pull logs or something to figure that out?

Thanks!

<img width="752" alt="Screen_Shot_2021-06-05_at_7_53_13_am" src="https://user-images.githubusercontent.com/21790/120866481-62b91480-c5d3-11eb-8535-ec680ed37ef6.png">

**Comment by jmgasper** [comment] 2021-06-04 21:55
Challenge https://www.topcoder.com/challenges/8b481f60-069d-462b-ac6f-b9a0df18181e has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2021-06-05 13:24
@jmgasper I can reproduce it. I'll fix a challenge forum processor. 
I'll look at a few more columns in the database and we can probably figure out which accounts were created this way.

_How reproduce it_
Create a new account, don't navigate to Topcoder Forums and register for a challenge:

![image](https://user-images.githubusercontent.com/10196632/120893124-2957c780-c61a-11eb-8762-b6ad9e950102.png)

**Comment by atelomycterus** [comment] 2021-06-05 17:44
@jmgasper The 'Vanilla Member' role (type='member') is only added by default  +  Topcoder roles (type='topcoder') if user hasn't been created in Vanilla.  

PR- https://github.com/topcoder-platform/challenge-forum-processor/pull/61. Thanks!

You can change `DEFAULT_MEMBER_ROLES` if you want. The default value is `['Vanilla Member']` (array of Vanilla role names).

https://github.com/topcoder-platform/challenge-forum-processor/blob/893d5b13186b34f966183b43e52a3f9da3561576/src/constants.js#L63
```
 VANILLA: {
    DEFAULT_MEMBER_ROLES: ['Vanilla Member'],

}
```
### Testing
Create a role  (type='member') in Vanilla. Create a new user  using topocder-dev.com and register for a challenge. 
Verify roles for a new user in Vanilla.

### Additional Notes
If you plan to create new users using Vanilla REST API/ other Vanilla methods (social connection/invitation, etc). Please verify it in DEV firstly. While analyzing the code, I noticed that in some cases, if a list of roles was not specified during  inserting an user, all roles with the 'member' type will be assigned to the user. May cause unexpected behavior or grant more permissions than expected.

**Comment by jmgasper** [comment] 2021-06-05 21:43
Payment task has been updated: https://www.topcoder.com/challenges/8b481f60-069d-462b-ac6f-b9a0df18181e
*Payments Complete*
Winner: obog
Copilot: ghostar
Challenge `8b481f60-069d-462b-ac6f-b9a0df18181e` has been paid and closed.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2021-06-05 21:43 UTC
Labels: Ready for QA, tcx_Assigned, tcx_FixAccepted

**Comment by sdgun** [comment] 2021-06-07 06:39
@atelomycterus @jmgasper FYI Created a new user in Dev to verify this issue(user handle - testvffortc) but this user cannot register to any challenge, looks like there are issues with the new users. I am checking this with @drasticdpk I will verify once this is fixed.

**Comment by sdgun** [comment] 2021-06-08 03:30
Verified in Dev.

1. Created role (type='member') in Vanilla from vanilla app UI
2. Created a new user using topocder-dev.com and registered to a challenge.
3. Verified the roles for the new user in Vanilla

Observation: Active gig workers role is not added

![image](https://user-images.githubusercontent.com/4592712/121118681-ea9f5880-c837-11eb-896a-410d8d4704cb.png)

**Comment by sdgun** [comment] 2021-06-09 04:55
Keeping since this cannot be directly tested in production.
