### ISSUE TITLE
[$100] When an image is pasted in the editor window by a normal user, the error ribbon is shown in the editor

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#103] opened 2020-11-03 06:36 UTC
**Steps**
Go to the forums as a normal user (ex user- TopConnCustomer link - https://vanilla.topcoder-dev.com/)
Click New Discussion
Paste an image in the editor

**Actual result**
The error ribbon is shown in the editor

**Expected result**
The error ribbon should not be shown in the editor

[File attach error.zip](https://github.com/topcoder-platform/forums/files/5479570/File.attach.error.zip)

**Comment by jmgasper** [comment] 2020-11-03 06:58
Contest https://www.topcoder.com/challenges/30148426 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-03 06:58
Contest https://www.topcoder.com/challenges/30148426 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-03 06:58
@atelomycterus - I'm open to suggestions on this one.

**Comment by atelomycterus** [comment] 2020-11-04 16:53
@jmgasper 'Allow File Uploads' Vanilla permission is used for any files (attachments/images). 
Each category has 'Allow File Uploads' and  users are not allowed to upload any files by default.  

We've implemented Roles setup for attachments (https://github.com/topcoder-platform/forums/issues/60):
> We'll also need to set up some defaults, for instance:
> Regular members will not be able to attach files to posts
> Copilots will be able to attach files to posts
 
So all files from an editor are uploaded via Vanilla REST API (/v2/media). If user is allowed to upload images then we need to fix \Vanilla\package\applications\dashboard\controllers\api\MediaApiController. At least check for image file types.

So let me know if regular members (Vanilla member role) are allowed to upload images for any category or a specific category.

**Comment by jmgasper** [comment] 2020-11-04 21:12
@atelomycterus - Regular members will *not* be allowed to upload images at all, for any category (at least at this current time).

@rootelement ☝️ Correct me if I'm wrong.

**Comment by rootelement** [comment] 2020-11-06 14:15
Correct

**Comment by jmgasper** [comment] 2020-12-01 22:22
@atelomycterus - If you need anything else here, let me know, thanks!

**Comment by atelomycterus** [comment] 2020-12-04 06:37
@jmgasper I wanted to reproduce this issue in DEV but I noticed that posting format is text. Rich Editor has a simple view in DEV. If post format is text then user can't upload images/attachments. Let me know if we are going to use Rich format. I'll update FormatInput in config.php. 

![image](https://user-images.githubusercontent.com/10196632/101129865-73cc9d00-3613-11eb-8387-87c6e2796c5b.png)

![image](https://user-images.githubusercontent.com/10196632/101129688-20f2e580-3613-11eb-9bd2-e9013e4accc7.png)

**Comment by jmgasper** [comment] 2020-12-04 10:57
@atelomycterus - Not sure what happened there.  I just turned the rich editor off and on again and it appears to be working now.

**Comment by jmgasper** [comment] 2020-12-04 20:52
@atelomycterus - Yeah, I think if we can just say something like `You don't have permission to upload files`, that would be good.  Sorry about the format problem - that was my fault.  Thanks for fixing that.

**Comment by atelomycterus** [comment] 2020-12-04 21:53
@jmgasper PR-https://github.com/topcoder-platform/forums/pull/266 - update a message in the Rest API. Unfortunately, need to fix and rebuild frontend because the editor displays  the hard-coded error message.  We have several frontend issues. I'm going to fix them  tomorrow.
![image](https://user-images.githubusercontent.com/10196632/101218224-bf269000-3693-11eb-9310-4ec0edc307b2.png)

![image](https://user-images.githubusercontent.com/10196632/101218362-fe54e100-3693-11eb-882f-8cb19b634c18.png)

**Comment by atelomycterus** [comment] 2020-12-05 16:22
@jmgasper Ready for review. Please apply PR-https://github.com/topcoder-platform/forums/pull/269. Thanks!

### Testing 
Clear browser cache before testing.

![image](https://user-images.githubusercontent.com/10196632/101250078-84be0100-372e-11eb-9a5c-615113024dfd.png)

**Comment by jmgasper** [comment] 2020-12-05 21:10
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30148426<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2020-12-05 21:10 UTC
Labels: Dev env, P4, bug, tcx_Assigned, tcx_FixAccepted, tcx_ReadyForReview

**Comment by sdgun** [comment] 2020-12-07 07:20
Verified. After clearing cache, the given message is shown when drag and drop files. Pasting is disabled. However it seems like the file is being attached first and then the error is displayed. 

[Screencast 2020-12-07.zip](https://github.com/topcoder-platform/forums/files/5651023/Screencast.2020-12-07.zip)
