### ISSUE TITLE
[$30] The default created Announcement in the code documents is not shown in the Announcements section until another discussion is announced

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#258] opened 2020-12-03 06:11 UTC
**Steps**

1. Log in as copilot user and go to a newly created challenge forum and check the announcements(no announcements even though there is an announcement which is created by default in the code documents) ex- https://vanilla.topcoder-dev.com/group/230
2. Now create a new discussion and announce it
3. Check the announcements section now

The newly announced discussion and default discussion both appears in the Announcements now

[Screencast 2020-12-03.zip](https://github.com/topcoder-platform/forums/files/5634011/Screencast.2020-12-03.zip)

**Comment by jmgasper** [comment] 2020-12-03 09:08
Contest https://www.topcoder.com/challenges/30155620 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-12-03 09:08
Contest https://www.topcoder.com/challenges/30155620 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2020-12-03 11:48
@jmgasper @sdgun I've noticed missing announcements. Group page doesn't display announcements until new ones are created in a category. It happens due to cache. Vanilla caches  announcement IDs by a category.  
I already found where the problem is happening. I'fix it.
```
    $categoryID = val('d.CategoryID', $wheres, 0);
     // Get the discussion IDs of the announcements.
    $cacheKey = $this->getAnnouncementCacheKey($categoryID);
    $this->SQL->cache($cacheKey);
    $this->SQL->select('d.DiscussionID')
         ->from('Discussion d');
```

Until today, Vanilla has not been configured with memcached. Data was always read from Database. Now Vanilla uses memcached in DEV. If you notice strange behavior or missing data, please create a ticket.
Maybe this is a problem with data caching. I've already faced a similar problem a couple of times. Thanks!

**Comment by atelomycterus** [comment] 2020-12-03 12:01
@jmgasper Fixed.  Please apply PR-https://github.com/topcoder-platform/forums/pull/262.

### Testing
The default created Announcement in the code documents should be displayed:
![image](https://user-images.githubusercontent.com/10196632/101015365-57c7ed80-3578-11eb-90f5-fb1c2c16f15c.png)

**Comment by jmgasper** [comment] 2020-12-03 21:29
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30155620<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2020-12-03 21:28 UTC
Labels: Dev env, P4, bug, tcx_Assigned, tcx_FixAccepted

**Comment by sdgun** [comment] 2020-12-04 05:54
Verified, the announcement appears by default.
