### ISSUE TITLE
[$40] Unable to bookmark discussions/post discussions or post comments, error in console

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#216] opened 2020-11-20 04:58 UTC
**Steps**
Go to a newly created challenge forum ex-https://vanilla.topcoder-dev.com/categories/bf6d0efd-b4f8-4846-a7df-82227d4248ff-documents - user -TCConnCopilot or any
Click bookmark icon

Bookmarking is not working, below error in console

[Bookmark issue.zip](https://github.com/topcoder-platform/forums/files/5571321/Bookmark.issue.zip)

![image](https://user-images.githubusercontent.com/4592712/99761210-8a56fc80-2b1b-11eb-98c3-b503e60ceac6.png)

![image](https://user-images.githubusercontent.com/4592712/99760992-09980080-2b1b-11eb-81f7-5590c8f68769.png)

![image](https://user-images.githubusercontent.com/4592712/99761470-36004c80-2b1c-11eb-97b5-7ce9c50e2b8e.png)

**Comment by sdgun** [comment] 2020-11-20 05:23
This error is thrown when posting new discussions too

![image](https://user-images.githubusercontent.com/4592712/99762463-93959880-2b1e-11eb-8505-9e6072d2851e.png)

**Comment by jmgasper** [comment] 2020-11-20 05:50
Contest https://www.topcoder.com/challenges/30152363 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-20 05:50
@atelomycterus - Any thoughts on why this might be failing?

**Comment by jmgasper** [comment] 2020-11-20 05:52
Contest https://www.topcoder.com/challenges/30152363 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2020-11-20 05:57
@jmgasper These issues are due to a debug bar. I was using it to view a debug info and @sdgun was testing.
I usually enable it when I can't reproduce a bug in my local env. After 2-5 mins I disable it again. 
@sdgun please let me know your working hours. I will try to turn it on only when it does not fall within your working hours

**Comment by sdgun** [comment] 2020-11-20 06:02
@atelomycterus I am usually working IST 9.30am-1.30pm

**Comment by jmgasper** [comment] 2020-11-21 06:16
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed by jmgasper** 2020-11-21 06:16 UTC
Labels: Dev env, P0, QAverified, bug, tcx_Assigned
