### ISSUE TITLE
[$1200] Creating comments and discussions seems to be taking more time than it used to be

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#381] opened 2021-02-09 16:35 UTC
**Steps**
Create a comment/discussion in challenge forum or roundtables and monitor the time it takes

Noticed these actions are taking more time as shown in the below screen shots:

Discussion Prod:

![Discussion Prod](https://user-images.githubusercontent.com/4592712/107395503-e467cc80-6b22-11eb-88b6-fa9818362bc1.PNG)

Discussion Dev:

![Discussion Dev](https://user-images.githubusercontent.com/4592712/107395513-e6319000-6b22-11eb-99f1-23adfbd060cd.PNG)

Comment Prod:

![Comment Prod](https://user-images.githubusercontent.com/4592712/107395515-e6ca2680-6b22-11eb-9271-02fb310b46f3.PNG)

Comment Dev:

![Comment Dev](https://user-images.githubusercontent.com/4592712/107395516-e762bd00-6b22-11eb-845d-c9151d34ced9.PNG)

**Comment by jmgasper** [comment] 2021-02-09 21:09
Challenge https://www.topcoder.com/challenges/2d61ee7a-b52f-4fb2-94af-c917614755d4 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2021-02-09 21:09
Challenge https://www.topcoder.com/challenges/2d61ee7a-b52f-4fb2-94af-c917614755d4 has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2021-02-11 05:10
@atelomycterus - This is becoming more of a concern.  Is there anything I can do in prod to help you debug this?

**Comment by atelomycterus** [comment] 2021-02-11 07:48
@jmgasper I'm going to work on it after #376, #377. The screens show that there are delays on both envs. I'll add php-xdebug and enable a profiler in a dockerfile. It helps to investigate performance issues. 

> Is there anything I can do in prod to help you debug this?

You may need to copy dump files. I'll analyze them.

Also, the flood settings can increase the posting time. The flood control settings - https://vanilla.topcoder-dev.com/vanilla/settings/floodcontrol.

**Comment by jmgasper** [comment] 2021-02-11 08:27
@atelomycterus - Thanks.  I've bumped up the flood control settings in prod so I'll keep an eye on it to see if that makes a difference.

**Comment by atelomycterus** [comment] 2021-02-13 21:57
@jmgasper I am working on it. 
### Adding comment and updating comment meta-data
Adding a comment takes  about 400-600 ms. The issue with the second ajax request which inserts/updates meta-data about the comment (user activity, count of comments, who added/edited the comment,... ) +  sends notifications. The second ajax requests works too long. 36 Notifications were not sent from 12 Feb in DEV. This request may take a long time due to PhpmailerException.

TODO: Check server logs in DEV + Need to profile the code. 

![image](https://user-images.githubusercontent.com/10196632/107862380-adb0ef80-6e5d-11eb-9fb4-bb0c402d00f1.png)
```
    /** Activity status: The activity sent just fine. */
    const SENT_OK = 2;
    /** Activity status: The activity is waiting to be sent. */
    const SENT_PENDING = 3;
    /** Activity status: The activity could not be sent. */
    const SENT_FAIL = 4;
    /** Activity status: There was an error sending the activity, but it can be retried. */
    const SENT_ERROR = 5;
```	
Reproduced in PROD/DEV. It returns 502 Bad Gateway in PROD. It returns 504  in DEV.  
![image](https://user-images.githubusercontent.com/10196632/107861810-5d379300-6e59-11eb-86af-ec8c171fdfdd.png)
![image](https://user-images.githubusercontent.com/10196632/107861861-b30c3b00-6e59-11eb-9f9a-c0186cc161c5.png)

### Adding discussion
I clicked on 'Post Discussion' in PRO/DEV but there were 2 requests (saving draft  and posting discussion). Not reproduced it locally. 
TODO: Need to debug it on client side.
![image](https://user-images.githubusercontent.com/10196632/107862218-6bd37980-6e5c-11eb-8e54-133183a6dde3.png)

**Comment by atelomycterus** [comment] 2021-02-14 22:12
@jmgasper  We've optimized viewing pages, but this issue exists with posting a discussion/comment. 

I ran locally with 50+ category, no issues, then I ran with the old Vanilla DB (500+ categories). It  works slower. Both issues are reproduced periodically. 

Could you provide DB from DEV (there are 1700+ categories, 6400 comments, 2400 discussion)? 

### Adding discussion and the second request
> I clicked on 'Post Discussion' in PRO/DEV but there were 2 requests (saving draft and posting discussion). Not reproduced it locally.

This issue is reproduced periodically (500+ categories). If a discussion is added at the nested category (level 5). 
If User clicks on 'Post Discussion' and the response has not yet been received because it is slow to execute.
In 60 secs the second request (saving drafts) happens because autosaving runs after 60 secs after typing text. 
If  posting a discussion works acceptable time,  no issue.

### Posting a discussion/comment

I ran it with the profiler locally with old Vanilla DB (~500+categories) . It generates 900+MB files per a request for discussion and 400+MB for comment. 

- Insert a discussion/comment. This part works quickly.
- Update meta data and rebuild cache:
 --Adjust the aggregate post counts for a category. It means get all ancestors for a category
 and iterate through the category and its ancestors, adjusting aggregate counts, update LastXXX fields.
(e.g. 'Challenges Forum › Data Science Forums › DS F2f 11 23 2020 › Code Questions')
![image](https://user-images.githubusercontent.com/10196632/107889209-08ac1a80-6f22-11eb-9780-5dc7c021b78f.png)

-- Update Category Cache by CategoryID: 
--- remove this category from  memcached
--- build cache for a category from a scratch. 
--- build category tree for the current user based user's permissions. 

From Profiling Viewer:
![image](https://user-images.githubusercontent.com/10196632/107890455-4ad95a00-6f2a-11eb-8e29-808c374f90d0.png)

![image](https://user-images.githubusercontent.com/10196632/107890470-5af13980-6f2a-11eb-8a13-c98ce1bf4baf.png)

**Comment by atelomycterus** [comment] 2021-02-15 22:28
Adding a comment/discussion re-builds cache only for  a category + all ancestors. Adding a comment/discussion in 'Challenge discussions' category rebuilds cache for 4 categories.  The main performance issue is calculating user permissions for a category in setCache. setCached is called 24 times for 4 categories. As a result, checkPermissions is called more than 80K+. 
TODO: When adding a discussion or comment, the user's permissions to the category will not change.  In this case, there is no need to recalculate everything from scratch. The only difference is LastXXX, CountXXX columns. 


![image](https://user-images.githubusercontent.com/10196632/107996439-76734780-6ff1-11eb-95fe-d40fb39215a2.png)

With adding a new comment, it works slower and slower. Adding 9 comments: 
![image](https://user-images.githubusercontent.com/10196632/107997688-6ad55000-6ff4-11eb-814a-06a17c51f42b.png)


For the first comment: avg 0.15 for each category:  CategoryModel.setCache:return4(), {"execution time (seconds)":0.14945220947265625,"CategoryID":1175}"
...
CategoryModel.setCache:return4(), {"execution time (seconds)":0.5750300884246826,"CategoryID":2335}"
...
CategoryModel.setCache:return4(), {"execution time (seconds)":1.0097100734710693,"CategoryID":1176}
...
For the 8 comment: avg 1.3-1.55, CategoryModel.setCache:return4(), {"execution time (seconds)":1.5211551189422607,"CategoryID":2335}"

**Comment by atelomycterus** [comment] 2021-02-15 22:38
@jmgasper  ☝️ This also leads to a huge amount of requests to Memcached. 
Could Topcoder give us access to monitoring memcached metrics? If we had access, we could quickly notice it.

**Comment by atelomycterus** [comment] 2021-02-15 22:39
@jmgasper Only for DEV env.

**Comment by atelomycterus** [comment] 2021-02-16 21:48
@jmgasper  I ran adding comments using a selenium script.  I commented our custom code and ran without checking Group permissions. I wanted to check the execution time of the original code.

When a comment is added:
- the first request  -  insert a record in DB (/?discussions=XXX)
- the second request  - adjust the aggregate comment counts for a category + ancestors,  update LastXXX fields in DB and rebuild the category cache (remove a category from memcached, build cache for a category from a scratch) and build category tree for the current user based user's permissions. In the screen/video, MAX category depth is 4 (adding a comment to a challenge forums's discussion). So it clears and rebuild  cache for 4 categories only.

![image](https://user-images.githubusercontent.com/10196632/108123226-91f45600-70b6-11eb-9d8a-99b35509085d.png)

See the video https://youtu.be/JndU9Y2ufnY.  

Count Of Categories in DB:
![image](https://user-images.githubusercontent.com/10196632/108122601-979d6c00-70b5-11eb-9044-ad8225cd40c5.png)

Adding a comment, with delay 3 secs, after several seconds usage CPU - 100% . 
![image](https://user-images.githubusercontent.com/10196632/108122995-3aee8100-70b6-11eb-929c-4c6a5c3efe97.png)

**Comment by jmgasper** [comment] 2021-02-16 22:07
@atelomycterus - Ok, thanks for that.  So, if I understand this right, this is a problem with Vanilla?  Have they released any new versions recently that we could test to see if the problem is resolved?

**Comment by atelomycterus** [comment] 2021-02-16 22:20
@jmgasper  
> So, if I understand this right, this is a problem with Vanilla?

yes. Vanilla Team has tried to improve caching functionality https://github.com/vanilla/vanilla/pull/8062. I've seen some issues with memory exhaustion (https://github.com/vanilla/vanilla/pull/7843 and others). Some issues have been fixed, other issues  are still open/hold.

The same issue https://open.vanillaforums.com/discussion/38113/vanilla-forum-take-high-cpu-usage, but no replies.

> Have they released any new versions recently that we could test to see if the problem is resolved?

New release - https://open.vanillaforums.com/discussion/38573/vanilla-2021-003-rc2-is-now-available but  it is not intended for use in production environments.

> Same as RC1, there are some warnings and considerations I'll repeat here:
This is an RC (release candidate). It is not intended for use in production environments. It is pre-release software. Install it in some kind of sandbox and go nuts, but avoid overwriting your existing Vanilla installs. Once we're confident in Vanilla 2021.003 on open-source community sites, we'll drop a production-ready release. Future updates probably won't need an RC cycle, but given the length of time since the last release, it seems prudent.

**Comment by jmgasper** [comment] 2021-02-16 22:24
Ok, thanks.

**Comment by atelomycterus** [comment] 2021-02-17 06:48
@jmgasper I am going to work on it today. 
- why the CPU usage is high
- test our custom Vanilla and profile code using different server configurations (opc, memcached and so on),  the main focus on adding comments / posts.
- do the same with Vanilla 3.3 (no customizations)

Keep you updated.

**Comment by atelomycterus** [comment] 2021-02-17 21:24
@jmgasper I've configured [tideways](https://tideways.com/). This is highly integrated PHP Profiling, Monitoring and Exception Tracking solution. 
Free Trial - 30-days. Can we configure it in DEV env for at least 30 days?  This has minimal system impact unlike xdebug.
Need to create an account and set the API key in Docker. I've set up it in Docker with Compose.

I've optimized a little our custom. All tests with delay 3 secs. The main problem is rebuilding category cache.

### 1879 categories
 Before any changes, memory usage was about 35MB-48MB per request (adding a comment):
![image](https://user-images.githubusercontent.com/10196632/108265696-283d8000-717a-11eb-8113-1bad4f10e94e.png)

After changes, memory usage is about 18MB-40MB per request (adding a comment): 
![image](https://user-images.githubusercontent.com/10196632/108266286-f842ac80-717a-11eb-9e3a-14a3bb4838fa.png)

Memory usage per request: 
![image](https://user-images.githubusercontent.com/10196632/108267022-e1e92080-717b-11eb-8794-32da51cb8c2c.png)

![image](https://user-images.githubusercontent.com/10196632/108268607-d4cd3100-717d-11eb-81ce-ad50637824e7.png)


### 48 categories
48 categories, adding comments -  300-400 ms with our custom code. 
![image](https://user-images.githubusercontent.com/10196632/108265958-8d917100-717a-11eb-9d91-30d6d92f370a.png)

**Comment by jmgasper** [comment] 2021-02-17 21:27
@atelomycterus - Sounds good, thanks!  I'll discuss with Topcoder about configuring tideways in dev.  I'm hoping they'll be willing to pay for it in dev.

**Comment by atelomycterus** [comment] 2021-02-18 21:53
@jmgasper  

###  CPU usage 100%
CPU usage is 100% due to running PHP GC.  After 2-3 requests (adding comment/discussions), CPU usage is high. As a result, we periodically notice that it works slowly or 502/504 error is displayed.

Another case when Vanilla works slowly -  clicking on  'development-forums'. The page displays 300 children. Need to check if  Vanilla has config param or hard-coded value is used in the code. 
![image](https://user-images.githubusercontent.com/10196632/108419814-0c061580-7244-11eb-8d81-1779c306f77c.png)

### Main Issues 
I am working on this part. These two issues lead to 100% CPU usage.
1. using array_unshift, array_reverse and other PHP functions which have O(n) complexity when setCache is called (building User Category Tree, calculating aggregated columns (CountDiscussions, CountComments) and so on). The more nested categories, the slower Vanilla works. If we can simplify it is better to do it.

2. adding a comment  at the challenge category (category depth = 4).  Only 4 categories are changed (LastInserted, CountComments and other firleds are updated) and there should be 4 calls of setCache(categoryID), called 24!
There are several methods (incrementAggregateCount, setAsLastCategory, updateLastPost and others) and each method updates different fields in DB and cache. The functionality was implemented at different times, some methods were implemented in Vanilla 2.X, others were implemented in Vanilla 3.X. Need to refactor the code and avoid excessive cache updates.
 
### PHP 7.3 garbage collector
PHP GC has improved notably in the 7.3 release of PHP, especially for an application with a large number of objects.
I've tried to run Vanilla with PHP 7.3 but it throws 'PHP message: PHP Fatal error:  Allowed memory size of 1073741824 (1800+ categories)) when I just added one comment!
![image](https://user-images.githubusercontent.com/10196632/108418461-5c7c7380-7242-11eb-95a0-03664feb0dd3.png)

Vanilla 3.3 supports PHP 7.2-7.4. After fixing the main issues, need to optimize PHP GC usage.  Until the main issues are solved, it has no sense to optimize and tune it.

**Comment by jmgasper** [comment] 2021-02-18 23:44
@atelomycterus - Thanks for the update.  I've bumped the payment again since this is taking a lot of work.  If I need to bump further, please let me know.

**Comment by atelomycterus** [comment] 2021-02-19 06:59
@jmgasper  Thanks! One more thing to do to make Vanilla work better with archived categories. Category has Archived flag, GDN_Category table. It has added in Vanilla 3.X. Now Vanilla loads all categories from DB including archived ones to build category cache.

In our case most categories are created in 'Challenges Forum' (https://vanilla.topcoder-dev.com/categories/challenges-forums).
 1. Let me know if (/groups/{id}/archive) is called in PROD/DEV.
 2. When is Archived flag set for a group? Whether this flag is set immediately when the challenge is completed? 

 (/groups/{id}/archive) sets the Archived flag for the group and Archived flag for all its categories. This has been implemented (https://github.com/topcoder-platform/forums/issues/136). 
 
 After fixing the main issues, try to load non-archived categories in cache by default. 
  3. How many active challenges are there at the same time? 
  For example, 'Development Forums', 3 categories are created per a group, 600 groups => 1800 categories are added in cache 
  If there are only 100 active Topcoder challenges (not completed) =>  100 groups x 3 = 300 categories should be added only in cache.

**Comment by jmgasper** [comment] 2021-02-19 07:20
1.  We don't have this deployed *yet*, but it will be soon, for the admin tool.  Support will be able to archive the forums for completed challenges
2. See above - we'll do this manually (for now), when a challenge completes
3. We should probably set a relatively high limit on this, if possible, especially since we haven't archived any forums just yet.

**Comment by atelomycterus** [comment] 2021-02-19 09:46
@jmgasper I understood.  Another piece of the setCache() method that greatly affects performance is the recalculation of Recent child posts for Nested Categories. This is a recursive function that use PHP functions with O(n) (array_unsfit and so on) to calculate the next fields: 
```
                $category['LastCommentID'] = $lastCategory['LastCommentID'];
                $category['LastDiscussionID'] = $lastCategory['LastDiscussionID'];
                $category['LastDateInserted'] = $lastCategory['LastDateInserted'];
                $category['LastTitle'] = $lastCategory['LastTitle'];
                $category['LastUserID'] = $lastCategory['LastUserID'];
                $category['LastDiscussionUserID'] = $lastCategory['LastDiscussionUserID'];
                $category['LastUrl'] = $lastCategory['LastUrl'];
                $category['LastCategoryID'] = $lastCategory['CategoryID'];
```

In general, it is now clear, where the main problematic pieces of code are. Let's try to optimize step by step.

### Tideways

PR with Tideways - https://github.com/topcoder-platform/forums/pull/417. Please add the env params, create a service and then deploy PR. Let me know if you need help.

1. The following env parameters should be added: 

`TIDEWAYS_APIKEY`=<API KEY> , Go to https://app.tideways.io/o/Topcoder/Discussions/settings , scroll to `API Key` section:
![image](https://user-images.githubusercontent.com/10196632/108481798-acdaec00-72a9-11eb-91d9-3f2a6ac82808.png)

`TIDEWAYS_SAMPLERATE`=25 - The percentage of how many requests are executed with the Timeline Profiler activated ("being sampled").
When Tideways is enabled, it runs on every request. The sample rate then influences if a full trace is collected including calls to frameworks, SQL, 
caches and other services via HTTP. When no full trace is collected, Tideways still reports the response time of the request and watches out for potential Exceptions and Fatal Errors. 
This allows you to get a full picture of your project including the full distribution of response times to every endpoint/transaction.
By default the sample rate for full traces is configured at 25% of all PHP requests and Tideways is automatically started on web requests.



2. Create service 'vanilla':
 I don't have permissions to create a service :
![image](https://user-images.githubusercontent.com/10196632/108482399-7ea9dc00-72aa-11eb-9613-b5169b45dcb8.png)

 Please create a service.  Go to https://app.tideways.io/o/Topcoder/Discussions/settings/services:

![image](https://user-images.githubusercontent.com/10196632/108482113-1b1fae80-72aa-11eb-8c25-87bd65bbef8e.png)

The service name should be `vanilla`:
![image](https://user-images.githubusercontent.com/10196632/108482281-5621e200-72aa-11eb-8019-bf8b35fba038.png)

3. Testing

After deploying you should see the lines: 
![image](https://user-images.githubusercontent.com/10196632/108482638-c9c3ef00-72aa-11eb-983f-2bcc2e28682a.png)

After viewing several Vanilla pages, you should see the lines: 
![image](https://user-images.githubusercontent.com/10196632/108482718-e6602700-72aa-11eb-8212-a2bca2cea6fd.png)

Wait for 3-5 secs, data should be displayed:
![image](https://user-images.githubusercontent.com/10196632/108483387-bb2a0780-72ab-11eb-8450-5769e9f62ad1.png)
 
### Using Tideways
All requests has Timeline and Summary. In my screen the first requests without tracing, so callgraph were not generated. It can be done by clicking on Trigger Trace button or using Chrome extension:
![image](https://user-images.githubusercontent.com/10196632/108486699-68eae580-72af-11eb-9d08-3771396b42e5.png)

Callgraph requires more resources, it's better trigger when it's required:
![image](https://user-images.githubusercontent.com/10196632/108487254-1cec7080-72b0-11eb-88c3-9e0bce5cc085.png)

**Comment by atelomycterus** [comment] 2021-02-19 11:11
@jmgasper 

> Another case when Vanilla works slowly - clicking on 'development-forums'. The page displays 300 children. Need to check if Vanilla has config param or hard-coded value is used in the code. ( from my comment https://github.com/topcoder-platform/forums/issues/381#issuecomment-781659016)

Created the issue - https://github.com/topcoder-platform/forums/issues/418

**Comment by atelomycterus** [comment] 2021-02-19 22:29
@jmgasper  I think that I will work on this task for 1-1.5 days. The cache is now being rebuilt 4 times (if 4 categories of the predecessor), instead of 24 times as it was before when the comment was created. It is necessary to make changes also for adding discussion.

![image](https://user-images.githubusercontent.com/10196632/108567590-940a1f00-7319-11eb-8a4c-adef9a194f38.png)

Before changes: Adding comment, delay 3 secs, 1879 categories, PHP memory_limit=512MB
![image](https://user-images.githubusercontent.com/10196632/108568293-e8fa6500-731a-11eb-8961-90ba194c2a7c.png)

Adding comments, delay 3 secs, 1879 categorie, PHP memory_limit=512MB: 
![image](https://user-images.githubusercontent.com/10196632/108567030-7be5d000-7318-11eb-8ae5-16d489e9e5d8.png)

After changes: Adding comment, delay 10 secs, 1879 categories, PHP memory_limit=512MB
![image](https://user-images.githubusercontent.com/10196632/108568063-77bab200-731a-11eb-8389-a78161041c5a.png)

**Comment by atelomycterus** [comment] 2021-02-21 16:31
@jmgasper Please apply PRs:
https://github.com/topcoder-platform/forums/pull/420
https://github.com/topcoder-platform/forums-groups-plugin/pull/58
https://github.com/topcoder-platform/forums-plugins/pull/61 

Thanks!

## Performance before and after changes
I deployed Vanilla without PRs to compare performance before and after changes.
 
### Discussions
Categories: 1879. 

Testing with a selenium script:
![image](https://user-images.githubusercontent.com/10196632/108631113-794ebc00-7479-11eb-81e6-5d90f6ca7117.png)

Call Graph:
![image](https://user-images.githubusercontent.com/10196632/108631008-e6158680-7478-11eb-914c-28d067736d3a.png)

### Comments
Testing with a selenium script, delay 3 secs.

**Before**: Post-proccesing after adding a comment:
![image](https://user-images.githubusercontent.com/10196632/108631248-f2e6aa00-7479-11eb-82dc-363acd437099.png)

**After**: Post-proccesing after adding a comment:
![image](https://user-images.githubusercontent.com/10196632/108631290-3214fb00-747a-11eb-8bc0-f09f6f795a3d.png)


**Call Graph**
![image](https://user-images.githubusercontent.com/10196632/108631230-d9456280-7479-11eb-829c-fbfa013c6cd5.png)

**Comment by atelomycterus** [comment] 2021-02-21 16:38
@sdgun @jmgasper Tideways supports Server-Timing API. So I've added it in Vanilla header. After deploying and configuring Tideways, click on/hover a green bar:
![image](https://user-images.githubusercontent.com/10196632/108631642-d8adcb80-747b-11eb-8cad-7764f53c980f.png)

You should see cache/http/php/sql:
![image](https://user-images.githubusercontent.com/10196632/108631727-54a81380-747c-11eb-83a0-c6bf128c2f0b.png)


Or the same in the header response:
![image](https://user-images.githubusercontent.com/10196632/108631614-ad2ae100-747b-11eb-9636-4f5cedec3a5d.png)

**Comment by atelomycterus** [comment] 2021-02-21 17:12
@jmgasper I see more performance bottlenecks in my local env. I think the same issues in DEV/PROD. Let's deploy Vanilla and monitor performance in DEV. 

- verify a token, it takes up to 900ms, avg 680-700 ms
Get requests:
![image](https://user-images.githubusercontent.com/10196632/108631950-879ed700-747d-11eb-860f-a6f0c810fc74.png)

![image](https://user-images.githubusercontent.com/10196632/108632137-625e9880-747e-11eb-82d2-2a49142fd3de.png)

**Comment by jmgasper** [comment] 2021-02-21 23:50
@atelomycterus - This looks good, thanks.  Deployed in dev.

I need to deploy to prod today, so if we need to back out anything for Tideways, just let me know.

**Comment by jmgasper** [comment] 2021-02-21 23:52
Payment task has been updated: https://www.topcoder.com/challenges/2d61ee7a-b52f-4fb2-94af-c917614755d4
*Payments Complete*
Winner: obog
Copilot: ghostar
Challenge `2d61ee7a-b52f-4fb2-94af-c917614755d4` has been paid and closed.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2021-02-21 23:51 UTC
Labels: Dev env, P1, bug, tcx_Assigned, tcx_FixAccepted

**Comment by sdgun** [comment] 2021-02-22 08:43
Verified in Dev, discussions/comments are created within 3-5 seconds now.

**Comment by sdgun** [comment] 2021-02-22 09:29
Verified in production, the discussions are taking around 8 seconds.

![image](https://user-images.githubusercontent.com/4592712/108689040-9e493a80-751e-11eb-8535-684c55367549.png)

**Comment by atelomycterus** [comment] 2021-02-23 19:44
@jmgasper Please apply PRs:
https://github.com/topcoder-platform/forums/pull/432
https://github.com/topcoder-platform/forums-groups-plugin/pull/60
Thanks. 

Important: Flush cache after deploying to avoid weird behavior (https://github.com/topcoder-platform/forums/issues/422#issuecomment-783250872). 

1. Please add `TIDEWAYS_APIKEY` env param (https://github.com/topcoder-platform/forums/issues/381#issuecomment-781962616). 
2. build,sh has been updated. Tideways-demon will run only in DEV.
```
if [ "$ENV" = "dev" ]; then
  ENV=$ENV CI_DEPLOY_TOKEN=$CI_DEPLOY_TOKEN docker-compose -f docker-compose.yml -f docker-compose.dev.yml build $APP_NAME
else
  ENV=$ENV CI_DEPLOY_TOKEN=$CI_DEPLOY_TOKEN docker-compose -f docker-compose.yml build $APP_NAME
fi
```

**Comment by jmgasper** [comment] 2021-02-23 22:03
@sdgun / @atelomycterus  - Deployed in dev.  I'm waiting on an update for the API env param

**Comment by atelomycterus** [comment] 2021-02-24 06:30
@sdgun  After updating env param I'll check that Tideways is displaying the data. Let's test this issue when Tideways is configured.

**Comment by jmgasper** [comment] 2021-02-24 06:36
@atelomycterus the Param should be set now.  I'm redeploying in dev which usually takes less than 10 minutes

**Comment by atelomycterus** [comment] 2021-02-24 07:01
@jmgasper Do you have permissions to create a service in Tideways (https://github.com/topcoder-platform/forums/issues/381#issuecomment-781962616)?

**Comment by sdgun** [comment] 2021-03-16 05:24
Verified in production, didn't observe a slowness.
