### ISSUE TITLE
[$30] Normal users can edit/delete the comments added by others

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#217] opened 2020-11-20 05:56 UTC
**Steps**
Log in to forums as a normal user (sdguntcqa)
Go to any available challenge forum discussion added by another user (https://vanilla.topcoder-dev.com/discussion/1751/baze-my-discussion#latest)
Click on ellipsis of a comment from another user

This user can perform edit/delete on it

![image](https://user-images.githubusercontent.com/4592712/99764505-3cde8d80-2b23-11eb-8413-a95c22c33fb6.png)

**Comment by jmgasper** [comment] 2020-11-29 02:27
@sdgun - I can't reproduce this.  Can you try again please?

**Comment by sdgun** [comment] 2020-11-30 07:05
@jmgasper This can be reproduced, checked by creating a post from TCConnCopilot in https://vanilla.topcoder-dev.com/discussion/1777/3rd and then log in as user sdguntcqa(pw-T0pc0der@123) 

[Delete comments issue.zip](https://github.com/topcoder-platform/forums/files/5614258/Delete.comments.issue.zip)

**Comment by jmgasper** [comment] 2020-11-30 20:38
Contest https://www.topcoder.com/challenges/30154852 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-30 20:39
@atelomycterus - I checked this in the permissions.  `sdguntcqa` has roles Vanilla Member and Topcoder User, but neither seem to have rights to edit comments / discussions - only add / view.

**Comment by jmgasper** [comment] 2020-11-30 20:40
Contest https://www.topcoder.com/challenges/30154852 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2020-11-30 21:11
@jmgasper yes, you are right. User doesn't have permisisons. I've checked what permisisons loaded:
![image](https://user-images.githubusercontent.com/10196632/100666008-62f8fe80-3369-11eb-812a-61541b11a3aa.png)

 I've found a bug in Vanilla CommentModel canEdit().

**Comment by atelomycterus** [comment] 2020-12-01 12:59
@jmgasper Fixed. please apply PRs:
https://github.com/topcoder-platform/forums/pull/249
https://github.com/topcoder-platform/forums-plugins/pull/51/
https://github.com/topcoder-platform/forums-groups-plugin/pull/35
Thanks!

### Testing
Don't use TonyJ account for testing because this account has several admin roles with Comments.Edit/Comments.Delete permissions. Please test with group members (copilot, member and so on)

Vanilla user/Topcoder User:
![image](https://user-images.githubusercontent.com/10196632/100743050-c710d680-33ec-11eb-9a29-b84fd2632cbf.png)

### How Vanilla works by default

The _Edit option_ is displayed if 
- User has 'Vanilla.Comments.Edit' permission
- Discussion is closed, but Moderators (role type= moderator) can edit comments
- User(Non-Moderator/Non-Admin) can edit if User is the author.
![image](https://user-images.githubusercontent.com/10196632/100742965-ae082580-33ec-11eb-9485-0d147e60316a.png)


The _Delete option_ is displayed if 
-  User has 'Vanilla.Comments.Delete' permission
-  User (Non-Moderator/Non-Admin) is the Author + `Vanilla.Comments.AllowSelfDelete`=true
'Vanilla.Comments.AllowSelfDelete' is false by default. So 'Delete'  shouldn't be displayed for  Vanilla User/Topcoder User.

**Comment by jmgasper** [comment] 2020-12-01 22:17
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30154852<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2020-12-01 22:17 UTC
Labels: Dev env, P1, bug, tcx_Assigned, tcx_FixAccepted

**Comment by sdgun** [comment] 2020-12-02 06:13
Verified from normal user, copilot, con admin and manager.
normal user(sdguntcqa)/manager(TCConManager) - can reply anyone's comments and edit his comments
copilot(TCConnCopilot) - can reply/delete anyone's comments and edit/reply/delete his comments
con admin(TCConAdmin) - can edit/reply/delete anyone's comments and his comments
