### ISSUE TITLE
[$40] 'Watching' count doesn't tally with actual watch list

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#523] opened 2021-04-02 06:07 UTC
Steps
Log in as sdguntcqa or adgunvfor users or from any user
Go to watching page
Check the number of watching categories and the actual count

'Watching' count doesn't tally with actual watch list
also for some users, it takes some time to update the count after first log in

![image](https://user-images.githubusercontent.com/4592712/113386224-68159b00-93a7-11eb-8bf1-f479936aad4f.png)

![image](https://user-images.githubusercontent.com/4592712/113386320-a317ce80-93a7-11eb-9b04-c86c526fae16.png)

**Comment by jmgasper** [comment] 2021-04-03 01:37
Challenge https://www.topcoder.com/challenges/45c758f7-5f58-4d34-af71-1ed91b7ef3fa has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2021-04-03 01:38
Challenge https://www.topcoder.com/challenges/45c758f7-5f58-4d34-af71-1ed91b7ef3fa has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2021-04-03 15:10
@sdgun 

 ** User sdguntcqa**
Total count is equal to 5 (3 categories,  2 bookmarks). The user registered for a challenge (https://vanilla.topcoder-dev.com/group/185), bookmarked 2 discussions and unregistered from the challenge. User unregistered in 20 November.  Count of Bookmarks is not correct. Count of Bookmarks should be 0.

We've fixed count of bookmarks after unregistering from challenges in 17 December (https://github.com/topcoder-platform/forums/issues/299#issuecomment-747203640). 

Using REST API  should fix the count of Bookmarks. (add `sdguntcqa`  to the group and remove from the group). Let me know if you need help with that. 

![image](https://user-images.githubusercontent.com/10196632/113480561-8493ff00-949d-11eb-9463-818d4371e948.png)
https://vanilla.topcoder-dev.com/discussion/1751/baze-my-discussion
https://vanilla.topcoder-dev.com/discussion/1753
![image](https://user-images.githubusercontent.com/10196632/113481344-a1cacc80-94a1-11eb-925a-6faa68cdb988.png)


** User sdgunvfor **
It looks like a bug.  The new column was added and count of watched categories should be calculated after updating User table. 
but the value is null for some users including `sdgunvfor`.  I'll fix it.

**Comment by atelomycterus** [comment] 2021-04-03 21:10
@jmgasper  Vanilla hasn't been started after deploying. I don't see any errors in logs:
```
2021-04-03 20:31:47,354 INFO stopped: apached (exit status 0)
[03-Apr-2021 20:31:47] NOTICE: Terminating ...
[03-Apr-2021 20:31:47] NOTICE: exiting, bye-bye!
2021-04-03 20:31:47,366 INFO stopped: php-fpmd (exit status 0)
2021-04-03 20:31:48,366 INFO waiting for syslogd to die
[SYSLOG] syslog-ng[43]: syslog-ng shutting down; version='3.13.2'
2021-04-03 20:31:48,468 INFO stopped: syslogd (exit status 0)
```
 Please PR-https://github.com/topcoder-platform/forums/pull/532. I commented a sql query. This query should be run before Vanilla bootstrap.  I am not sure but it might cause an issue.

**Comment by jmgasper** [comment] 2021-04-03 22:14
@atelomycterus - Deploying now

**Comment by jmgasper** [comment] 2021-04-03 22:28
@atelomycterus - The deploy is done and the app is working agin.

**Comment by atelomycterus** [comment] 2021-04-04 14:46
@jmgasper Please apply PR-https://github.com/topcoder-platform/forums/pull/534. Thanks! Mysql DB (DEV) uses `TRADITIONAL SQL` mode, which converts all warnings to errors.  I was able to reproduce it and got the same error locally. I've updated a sql query.

**Comment by jmgasper** [comment] 2021-04-05 01:25
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2021-04-05 01:26
Challenge https://www.topcoder.com/challenges/ee1ce89c-adb8-41f7-bdbc-067fc2389896 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2021-04-05 20:09
@jmgasper I am verifying this issue. The CountWatchedCategories wasn't updated.  I noticed you applied PR, deployed, reverted the commit and deployed again. 

Vanilla Bootstrap is done once on the first request. I checked Vanilla logs, there were no requests between 2 deploys, so the update sql wasn't executed.  

Please let me know if there were some reasons/issues to revert it.

**Comment by jmgasper** [comment] 2021-04-05 22:31
@atelomycterus - After deploying the first time (before the revert), the app failed to respond to requests - it just constantly threw 500 errors in dev.  I reverted that commit, redeployed and it worked.  Not sure why 🤷

**Comment by sdgun** [comment] 2021-04-06 04:33
> @sdgun
> 
> ** User sdguntcqa**
> Total count is equal to 5 (3 categories, 2 bookmarks). The user registered for a challenge (https://vanilla.topcoder-dev.com/group/185), bookmarked 2 discussions and unregistered from the challenge. User unregistered in 20 November. Count of Bookmarks is not correct. Count of Bookmarks should be 0.
> 
> We've fixed count of bookmarks after unregistering from challenges in 17 December ([#299 (comment)](https://github.com/topcoder-platform/forums/issues/299#issuecomment-747203640)).
> 
> Using REST API should fix the count of Bookmarks. (add `sdguntcqa` to the group and remove from the group). Let me know if you need help with that.

@atelomycterus Can you please provide me the Rest API details to add/remove this user?

**Comment by atelomycterus** [comment] 2021-04-06 07:06
@jmgasper I've updated Debug plugin. Please apply -https://github.com/topcoder-platform/forums-plugins/pull/83. Thanks!

> After deploying the first time (before the revert), the app failed to respond to requests - it just constantly threw 500 errors in dev. I reverted that commit, redeployed and it worked. Not sure why

The update query caused the 500 error. TRADITIONAL SQL mode converts all sql warnings to errors. So we get the 500 error when executing the update sql query. It might be due to some sql modes (NO_UNSIGNED_SUBTRACTION and others).  It looks like my local DB settings are different from DEV. 

The initial value of CountWatchedCategories should be calculated once for users.   Need to parse the preferences keys from string to int. `CAST` and other sql functions are used. Probably some sql functions create warinings during update:
![image](https://user-images.githubusercontent.com/10196632/113667732-dd3fe380-96b9-11eb-9b26-58ddc391a777.png)

**Comment by atelomycterus** [comment] 2021-04-06 07:18
@sdgun 
> @atelomycterus Can you please provide me the Rest API details to add/remove this user?

I've added `sdguntcqa` to https://vanilla.topcoder-dev.com/group/members/185. I let you know when you can verify other users. The issue with an update query exists.
![image](https://user-images.githubusercontent.com/10196632/113672618-ac16e180-96c0-11eb-8c7a-33735b994300.png)

**Comment by atelomycterus** [comment] 2021-04-06 11:54
@jmgasper Please apply PR-https://github.com/topcoder-platform/forums/pull/542. 

On Dev the previous update query completed with the error. I've rewritten it. Now it's working as expected.
![image](https://user-images.githubusercontent.com/10196632/113706549-7afdd780-96e7-11eb-8df5-5ebe54ae4887.png)

@sdgun You can verify this issue.

**Comment by jmgasper** [comment] 2021-04-06 22:45
Payment task has been updated: https://www.topcoder.com/challenges/ee1ce89c-adb8-41f7-bdbc-067fc2389896
*Payments Complete*
Winner: obog
Copilot: ghostar
Challenge `ee1ce89c-adb8-41f7-bdbc-067fc2389896` has been paid and closed.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2021-04-06 22:44 UTC
Labels: Dev env, March 2021 Shapeup, P3, Ready for QA, bug, tcx_Assigned, tcx_FixAccepted

**Comment by sdgun** [comment] 2021-04-07 04:44
Verified with multiple users, the watching list is showing the counts correct.

**Comment by sdgun** [comment] 2021-04-09 05:07
Verified in production with user CustomerUser, the counts tally with the list.
