### ISSUE TITLE
[$100] Prod - When posting a new comment in a thread, at times an older comment duplicates

### ISSUE THREAD

**Issue by ketzjs09** [topcoder-platform/forums#600] opened 2021-04-24 08:29 UTC
I have been noticing of the past couple of days that when I post a message in an existing thread, as soon as my message gets posted, a duplicate version of a random existing message appears right above the newly posted message. It vanishes only when the page is refreshed.

**Comment by jmgasper** [comment] 2021-04-24 23:48
Challenge https://www.topcoder.com/challenges/646e0afd-7114-4cbe-ac93-5f1ba1a7bba7 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2021-04-24 23:48
Challenge https://www.topcoder.com/challenges/646e0afd-7114-4cbe-ac93-5f1ba1a7bba7 has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2021-04-25 21:38
@ketzjs09  I am trying to reproduce this bug, but it works as expected. Could you record a video or provide screenshots? Please let me know what browser you are using. Thanks a lot for your time and help!

**Comment by jmgasper** [comment] 2021-04-26 22:00
@ketzjs09 - Any chance you could provide a screenshot / more details please?

**Comment by ketzjs09** [comment] 2021-04-27 08:08
Hi @jmgasper, I'm nowadays trying to keep my unpaid time donations to Topcoder to the minimum, so instead of spending time making video I'll describe textually what happened. 

I don't have any challenges running right now, so haven't tested it recently. I noticed this twice last week or so, once while posting in the copilot evolution thread and once in a challenge. In the evolution thread, I posted a second message within a span of 5 minutes and noticed the OPs message right above my second one, which confused me as in where did my 1st message go. Then when I scrolled up I noticed that the OP's message has been duplicated and has mysteriously appeared right above my 2nd message. This went away when I refreshed the page. 

In the second instance, my message was the 3rd message in the thread, and right after posting the 2nd message appeared twice, so it basically become 1st, 2nd, 2nd, 3rd instead of 1st, 2nd and 3rd. Again, this got rectified after a refresh.

**Comment by jmgasper** [comment] 2021-04-27 08:09
Ok, no worries thanks.  We'll use that to see if we can reproduce.  Thanks for taking the time to document this for us!

**Comment by ketzjs09** [comment] 2021-04-27 08:13
You're welcome.

**Comment by atelomycterus** [comment] 2021-04-27 19:27
@ketzjs09 Thanks a lot for your help! From the text description it looks like the old js files are in the browser cache. 
The recent changes were deployed on the twentieth of April. We changed updating comments after posting new ones. Please clear your browser cache. If there are any issues, do not hesitate to contact.

**Comment by jmgasper** [comment] 2021-04-27 21:47
Payment task has been updated: https://www.topcoder.com/challenges/646e0afd-7114-4cbe-ac93-5f1ba1a7bba7
*Payments Complete*
Winner: obog
Copilot: ghostar
Challenge `646e0afd-7114-4cbe-ac93-5f1ba1a7bba7` has been paid and closed.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2021-04-27 21:46 UTC
Labels: March 2021 Shapeup, P1, tcx_FixAccepted
