### ISSUE TITLE
[$50] When click Edit on a comment and cancel the edit window, the edit is not allowed until the page is refreshed

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#79] opened 2020-10-29 08:39 UTC
**Steps**
Go to the forum of a normal user(ex user- TopConnCustomer group - https://vanilla.topcoder-dev.com/group/128)
Add a comment 
Click edit(...) on the comment >> Click Edit
Cancel the edit 
Click edit(...) on the comment again

**Actual result**
The Edit option is not shown

**Expected result**
The Edit option should be shown

![image](https://user-images.githubusercontent.com/4592712/97545000-5ee76300-19f0-11eb-8f21-004112f26b2d.png)

**Comment by jmgasper** [comment] 2020-10-31 01:46
@sdgun - I can't reproduce this.  Can you add a video please?

**Comment by sdgun** [comment] 2020-10-31 06:44
@jmgasper Attaching the video

[Edit issue.zip](https://github.com/topcoder-platform/forums/files/5468619/Edit.issue.zip)

**Comment by jmgasper** [comment] 2020-11-02 05:52
Contest https://www.topcoder.com/challenges/30148095 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-02 05:52
Contest https://www.topcoder.com/challenges/30148095 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2020-11-02 16:24
@jmgasper Fixed (Vanilla bugs). PR-https://github.com/topcoder-platform/forums/pull/97. Thanks!

**Comment by jmgasper** [comment] 2020-11-04 01:24
Payment failed: [500]: Failed to get billing detail for the project.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by sdgun** [comment] 2020-11-06 06:53
Verified, this issue is fixed.

**Comment by jmgasper** [comment] 2020-11-06 06:57
Payment failed: [500]: Failed to get billing detail for the project.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-09 20:00
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30148095<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2020-11-09 20:00 UTC
Labels: QAverified, tcx_FixAccepted
