### ISSUE TITLE
[$200] Normal user does not have permission to Challenge discussions(registered and displayed in the CHALLENGE DISCUSSIONS page)

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#422] opened 2021-02-22 04:25 UTC
**Steps**
Log in from a normal user (ex- sdguntcqa/T0pc0der@123)
Go to https://vanilla.topcoder-dev.com/groups/mine?filter=challenge
Click on the listed challenge forums

The user doesn't have permission but user is registered to them

Ex group - https://vanilla.topcoder-dev.com/group/310
Above challenge's challenge details page - https://www.topcoder-dev.com/challenges/f65f8ffa-d698-4348-8213-61d5ebe8ac63

![image](https://user-images.githubusercontent.com/4592712/108662279-046c9800-74f4-11eb-97f2-a0fc08070b3e.png)

![image](https://user-images.githubusercontent.com/4592712/108662328-18b09500-74f4-11eb-8abc-260b8456b4cb.png)

Also in the https://vanilla.topcoder-dev.com/categories/challenges-forums, it shows some number of discussions/comments but inside the categories no challenges are available

![image](https://user-images.githubusercontent.com/4592712/108662827-2f0b2080-74f5-11eb-8381-6f751c18af8e.png)

![image](https://user-images.githubusercontent.com/4592712/108662843-37635b80-74f5-11eb-8c34-593370e25f15.png)

**Comment by sdgun** [comment] 2021-02-22 05:08
This behavior is a bit weird, then I created a new challenge and registered to it from the same user, after which all the challenge forums listed in the https://vanilla.topcoder-dev.com/groups/mine?filter=challenge were accessible to this user.

However for the user sdgunvfor/T0pc0der@123 who is a copilot user still has this issue. This user sees a challenge discussion here https://vanilla.topcoder-dev.com/groups/mine?filter=challenge but doesn't have permission to it.(Challenge - https://www.topcoder-dev.com/challenges/c14c541f-c61f-4bca-ac7e-4d199f157913)

![image](https://user-images.githubusercontent.com/4592712/108665086-181afd00-74fa-11eb-849e-f782f0600e9c.png)

![image](https://user-images.githubusercontent.com/4592712/108665100-210bce80-74fa-11eb-8d1d-60acb7579b09.png)

**Comment by jmgasper** [comment] 2021-02-22 07:24
Challenge https://www.topcoder.com/challenges/79ecd8cc-0e4e-4025-b8c5-c505ff79e427 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2021-02-22 07:24
Challenge https://www.topcoder.com/challenges/79ecd8cc-0e4e-4025-b8c5-c505ff79e427 has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2021-02-22 07:41
@jmgasper I've checked PROD.  

### PROD 
1. Guests.  Go to Guest Role and uncheck 'Discussions.View' for default Category.  'Challenge Discussions' should be hidden.
![image](https://user-images.githubusercontent.com/10196632/108677045-2cf79080-74fa-11eb-9c56-dcab1437c8aa.png)

**Comment by atelomycterus** [comment] 2021-02-22 07:42
@jmgasper 2. Also check Permissions for  'Challenge Discussions' category for Guest.

**Comment by jmgasper** [comment] 2021-02-22 07:47
@atelomycterus - Done, thanks.

**Comment by atelomycterus** [comment] 2021-02-22 09:58
@jmgasper  Please flush cache in PROD.

###  #DEV
1. Issue - 1 
Reason:  a develop branch with Issues-381 was deployed first.  GroupID is hash key in UserGroup cache,  checking isMemberOf  - constant-time performance O(1), not O(N).

> The user doesn't have permission but user is registered to them
Ex group - https://vanilla.topcoder-dev.com/group/310
Above challenge's challenge details page - https://www.topcoder-dev.com/challenges/f65f8ffa-d698-4348-8213-61d5ebe8ac63

![image](https://user-images.githubusercontent.com/10196632/108692354-8f0dc100-750d-11eb-8890-ea3c370252fa.png)

Now you should see:
![image](https://user-images.githubusercontent.com/10196632/108691008-122e1780-750c-11eb-8634-90ac895972eb.png)

FIX: flush cache. 

![image](https://user-images.githubusercontent.com/10196632/108692252-6c7ba800-750d-11eb-9759-6a1abe82151e.png)

**Comment by atelomycterus** [comment] 2021-02-22 10:01
@jmgasper '/cache/flush' - Debug plugin should be enabled. ☝️

**Comment by jmgasper** [comment] 2021-02-22 10:53
@atelomycterus - Done.

**Comment by atelomycterus** [comment] 2021-02-22 15:13
@jmgasper  

Issue -2:
> Also in the https://vanilla.topcoder-dev.com/categories/challenges-forums, it shows some number of discussions/comments but inside the categories no challenges are available

I was able to reproduce it in my local env. We disabled 'FollowingCategory' (https://github.com/topcoder-platform/forums/issues/372).
As a result, another flow is performed to determine which categories to show. 
In https://github.com/topcoder-platform/forums/issues/418 , I mentioned 'Vanilla.Categories.QueryLimit=300'. 
Now it gets only the 300 records of Development Challenges. I've changed limit and tested locally, 'Development forums' has 615 categories: 

![image](https://user-images.githubusercontent.com/10196632/108727231-64d1f880-7539-11eb-95e1-2a579a3dd28b.png)


### Testing DEV
Logged in as 'obogtop' (normal user). I can't see some challenge categories in DEV. 
![image](https://user-images.githubusercontent.com/10196632/108724792-c8a6f200-7536-11eb-968d-d3ede5df2dec.png)
 
### Reproduce it

**Comment by rootelement** [comment] 2021-02-22 17:50
@atelomycterus is this issue fixed then?

**Comment by rootelement** [comment] 2021-02-22 17:50
@sdgun please retest

**Comment by atelomycterus** [comment] 2021-02-22 18:43
@rootelement  
1. Issue-1 due to cache. @jmgasper Has flushed cache in PROD.
2. Issue-2:  Need to fix Categories Controller because it displays 300 categories ( Vanilla.Categories.QueryLimit=300). 
This problem can be seen if you click on 'Development Forums' in the breadcrumbs. If you don't have access permissions for the first 300 categories in 'Development Forums', then 'no categories' is displayed. This problem has not been noticed before.  There is no paging in Categories Controller.  

User can see his/her challenges from 'CHALLENGE DISCUSSIONS' because it supports paging.
![image](https://user-images.githubusercontent.com/10196632/108753600-01a28f00-7556-11eb-9b63-0582668be654.png)


Temporary solution:  $Configuration['Vanilla']['Categories']['QueryLimit'] = 450; The user will have access to the categories he has access to. 

'450' - because 'Development Forums' has '406' categories in PROD.  
I've checked PROD. Stats from PROD: 
[
  {
    "CategoryID": 3,
    "CountCategories": 406,
    "Name": "Development Forums",
  },
  {
    "CategoryID": 4,
    "CountCategories": 76,
    "Name": "Design Forums",
  },
  {
    "CategoryID": 5,
    "CountCategories": 42,
    "Name": "Data Science Forums",
  }
]

We cannot increase QueryLimit indefinitely, need to implement paging for Categories.

**Comment by atelomycterus** [comment] 2021-02-22 22:38
@jmgasper I am trying to fix Issue-2. 

The main problem is to display the categories correctly. The calculation of what permissions the user has on the category are calculated all in code, not in DB. There is a lot of logic here, because categories can be nested + users can have multiple roles.


I understand why they've added 'QueryLimit',  since all calculations are done in the code. This option is good when there is very little category 10-1000 in the system. In our case, the number of categories is much larger. I remember that in the documentation or on the Vanilla blog they wrote that if there is a large number of categories, then it is recommended to use Flat (Category type= Flat). I already found it and checked how it works.  The category page with paging is displayed, but checking permissions is ignored.

![image](https://user-images.githubusercontent.com/10196632/108779273-ae413880-7577-11eb-93d7-5ce8889ace9e.png)

User doesn't have permission to view, but it's displayed.
![image](https://user-images.githubusercontent.com/10196632/108779227-9b2e6880-7577-11eb-9725-099479771a5e.png)

**Comment by jmgasper** [comment] 2021-02-23 04:02
@atelomycterus - Ok, thanks for the update.

**Comment by atelomycterus** [comment] 2021-02-23 13:57
@jmgasper Please apply PR-https://github.com/topcoder-platform/forums/pull/431.

Need to change category type to 'Flat' for '_Development Forums_', '_Data Science Forums_', and '_Design Forums_'.
I fixed SQL query to support paging and Group permissions . Assuming that we have all challenge categories created by a challenge processor and tied to Group. It'll also work with regular groups.

Out category tree structure:
-Challenge Discussions (Nested)
--Development Forums (Flat).
---Challenge 1 (Nested), 
---Challenge 2 (Nested)
---Challenge 3 (Nested)
---Challenge N (Nested)
--Data Science Forums (Flat)
...
--Design Forums (Flat)
....

No changes for Roundtables or other categories:
-General (Nested). The category has several categories, paging support is not required.
--Gig Work Discussions (type=discussions, paging support out of the box)
--General Discussion  (type=discussions)

After changing category types, you should see a paging nav, 30 records by default, 
![image](https://user-images.githubusercontent.com/10196632/108851707-c9528d80-75f5-11eb-9f29-2279685e04e4.png)

Let me know if you have any questions.

Thanks!

**Comment by jmgasper** [comment] 2021-02-23 22:05
@atelomycterus  - I've deploy the PRs and update the settings in dev for the category type.

**Comment by jmgasper** [comment] 2021-02-23 22:06
Payment task has been updated: https://www.topcoder.com/challenges/79ecd8cc-0e4e-4025-b8c5-c505ff79e427
*Payments Complete*
Winner: obog
Copilot: ghostar
Challenge `79ecd8cc-0e4e-4025-b8c5-c505ff79e427` has been paid and closed.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2021-02-23 22:05 UTC
Labels: Dev env, P0, Ready for QA, bug, tcx_Assigned, tcx_FixAccepted

**Comment by atelomycterus** [comment] 2021-02-24 06:17
@jmgasper I've tested as a normal user (obogtop). It works as expected. 
>@atelomycterus - I've deploy the PRs and update the settings in dev for the category type.

**Comment by sdgun** [comment] 2021-02-24 06:53
Verified from below users, and challenge forums were visible without permission issues.

sdguntcqa
sdgunvfor
pshah_customer
TopConnCustomer

**Comment by sdgun** [comment] 2021-03-16 07:27
Verified in production.
