### ISSUE TITLE
[$40] Most recent shows incorrect user

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/forums#311] opened 2020-12-23 10:00 UTC
I arrived at the forums by first listing out all the challenges (in the forum sidebar) and then clicking on my challenge's forum.

Here, I see the most recent message was by me:

![image](https://user-images.githubusercontent.com/2317133/102984290-62502400-4533-11eb-9205-ec86b5f93039.png)

But when I open that post, I see that there is another user that has posted:

![image](https://user-images.githubusercontent.com/2317133/102984517-b65b0880-4533-11eb-935a-19ab9e75a88a.png)

**Comment by jmgasper** [comment] 2020-12-23 11:24
Contest https://www.topcoder.com/challenges/30160084 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-12-23 11:24
Contest https://www.topcoder.com/challenges/30160084 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2020-12-23 12:00
@callmekatootie Thanks! Could you provide a challenge link? I'll register for a challenge and have look at it.

Most recent by 'XXXX' is read from a calculated Vanilla column. The column should be updated after adding/editing comment/discussion. Previously, `Most recent by` displayed data when new records were only added.

**Comment by callmekatootie** [comment] 2020-12-23 12:06
This challenge - https://www.topcoder.com/challenges/bbbaae17-20ae-424f-ad8f-bec887b9a297

I have however added my response to that post - so you may not get to see what you are after... but feel free to play around. I will ignore your posts but do let me know if you are indeed participating and if it's a genuine question and I'll response :)

**Comment by atelomycterus** [comment] 2020-12-23 14:38
@callmekatootie @jmgasper The issue only at Category page. 'Most recent by' +data time is not correct  if a discussion has comments before deploying new version in PROD.

First I'll try to test it in DEV. If I can't reproduce it, need your help to execute several sql queries in PROD.
Keep you updated.

# Discussion with comments 
### Issue 1
I added a  comment.  Data time + most recent by - correct at categories page but Date time is displayed twice.
![image](https://user-images.githubusercontent.com/10196632/103002825-ad246880-4540-11eb-9562-2e729544f50d.png)

### Issue 2
'Most recent' wasn't updated at Category page. User is not correct. 'obog'  should be displayed. TODO: Check Vanilla code -  'LastCommentBy'
![image](https://user-images.githubusercontent.com/10196632/103001511-35553e80-453e-11eb-8281-e156b520caed.png)

### Issue 3
Local user time is shown. TODO: Check Vanilla code -  'LastCommentDate'

![image](https://user-images.githubusercontent.com/10196632/103004355-b3b3df80-4542-11eb-92eb-07d04c237339.png)


## Testing Updating comment

![image](https://user-images.githubusercontent.com/10196632/103003706-515adf00-4542-11eb-9fb4-7f3875e13f9c.png)

After updating comment . Date time +user  - correct at all levels.
![image](https://user-images.githubusercontent.com/10196632/103003371-bb26b900-4541-11eb-92df-326957c5e9b5.png)

This data  is correct too.
![image](https://user-images.githubusercontent.com/10196632/103003411-ced21f80-4541-11eb-8ebc-ab59e2621855.png)

This data  is correct too.
![image](https://user-images.githubusercontent.com/10196632/103003854-8f580300-4542-11eb-9ce0-858563cb271d.png)

# Adding the first comment 
If it's the first comment. It is displayed correctly at all category levels (from a challenge to Challenge Forums). 
![image](https://user-images.githubusercontent.com/10196632/103006806-608e5c80-4543-11eb-807a-c1182e0e2b6a.png)
 
![image](https://user-images.githubusercontent.com/10196632/103006949-97fd0900-4543-11eb-9ca9-77a81f718b50.png)

Updating the comment: 
![image](https://user-images.githubusercontent.com/10196632/103007365-53be3880-4544-11eb-9154-aba2f0aee038.png)

![image](https://user-images.githubusercontent.com/10196632/103007395-62a4eb00-4544-11eb-9c45-34fe28360a8a.png)

**Comment by callmekatootie** [comment] 2020-12-23 15:39
Thank you for looking into this. Let me know if you need any more info from me.

**Comment by callmekatootie** [comment] 2020-12-24 05:14
@atelomycterus If you need more data, register for this contest - https://www.topcoder.com/challenges/aaf99333-62e1-4723-830d-66e9291ce441.

Here, check out the post titled `Clarification on Spark requirement`.

![image](https://user-images.githubusercontent.com/2317133/103062691-f32b0c00-45d4-11eb-91db-b45c0ba8db91.png)

It says cagdas001 was the recent user but if you go in the thread, I am the last user to have posted...

**Comment by atelomycterus** [comment] 2020-12-24 18:20
@callmekatootie I see the same issue in DEV. Thanks a lot for your help!

**Comment by atelomycterus** [comment] 2020-12-24 20:32
@jmgasper Please apply PR-https://github.com/topcoder-platform/forums/pull/327. Thanks!

I'll test after deploying in DEV:
 
https://vanilla.topcoder-dev.com/categories/1b0c3322-a76f-4e8c-a821-efb1ad22a6d6
https://vanilla.topcoder-dev.com/categories/5eaf0e74-8ccc-40d1-9cc6-88b216c7b60b
https://vanilla.topcoder-dev.com/discussion/1521

- date time  should be correct 
- add new comment  => user should be correct

![image](https://user-images.githubusercontent.com/10196632/103103816-d45c6200-4634-11eb-94dc-b26eeb496bb5.png)
![image](https://user-images.githubusercontent.com/10196632/103103867-1be2ee00-4635-11eb-9b67-ec5139110494.png)

**Comment by jmgasper** [comment] 2020-12-24 22:07
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30160084<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2020-12-24 22:06 UTC
Labels: tcx_Assigned, tcx_FixAccepted, tcx_ReadyForReview

**Comment by sdgun** [comment] 2020-12-25 04:53
@atelomycterus I still see the last commented user incorrect, you can check in the below.  

Discussion: https://vanilla.topcoder-dev.com/discussion/1718/home-challenges-forum-development-forums-helis-web-1-code-documents-new-discussion

Category: https://vanilla.topcoder-dev.com/categories/c14c541f-c61f-4bca-ac7e-4d199f157913-documents

![image](https://user-images.githubusercontent.com/4592712/103119825-14563000-469b-11eb-969a-5c0112723ddb.png)

![image](https://user-images.githubusercontent.com/4592712/103119845-32239500-469b-11eb-9e4d-34c8ae07230e.png)

**Comment by atelomycterus** [comment] 2020-12-25 16:53
@sdgun Thanks!  I've fixed it in PR-https://github.com/topcoder-platform/forums/pull/328.

**Comment by atelomycterus** [comment] 2020-12-30 08:31
@sdgun I've tested it. 
Updating existing comment:
![image](https://user-images.githubusercontent.com/10196632/103339446-772c3a80-4a92-11eb-83fa-34ec73e8e34f.png)

Adding new comment:
![image](https://user-images.githubusercontent.com/10196632/103339485-8a3f0a80-4a92-11eb-9d5e-d7769c30d730.png)

**Comment by sdgun** [comment] 2020-12-30 09:15
@atelomycterus When a user edits someone else's comments we show the last comment by 'comment edited user' but the last comment inside the discussion is by someone else

Ex- 
![image](https://user-images.githubusercontent.com/4592712/103341024-ad29e880-4aab-11eb-8a01-ad4ef467422d.png)

https://vanilla.topcoder-dev.com/discussion/2200/dilhani-gunawardhana

**Comment by atelomycterus** [comment] 2020-12-30 09:33
@sdgun User is correct but you will see the name only after mouse hover.  I'll check Vanilla render functions.

![image](https://user-images.githubusercontent.com/10196632/103342377-6b447680-4a9a-11eb-90c3-e3739365d625.png)

![image](https://user-images.githubusercontent.com/10196632/103342395-74cdde80-4a9a-11eb-9b9e-b2988a380d79.png)

![image](https://user-images.githubusercontent.com/10196632/103342421-81eacd80-4a9a-11eb-913b-6e25676a616a.png)

**Comment by sdgun** [comment] 2020-12-30 09:48
@atelomycterus Got it, thanks

**Comment by atelomycterus** [comment] 2020-12-30 10:38
@jmgasper @sdgun I remember an username showed up after editing, but it could have been done via hooks in previous editors. I've added `by <username>` to the base Vanilla method. It needs to be displayed, not every user will hover over the phrase.

After PR-https://github.com/topcoder-platform/forums/pull/341: 
![image](https://user-images.githubusercontent.com/10196632/103345314-202e6180-4aa2-11eb-9457-9ab6a915a706.png)

**Comment by sdgun** [comment] 2021-01-22 08:19
Verified in production

https://discussions.topcoder.com/categories/ac34bef7-a634-4d2f-b5e4-c83f68d908a5-questions
