### ISSUE TITLE
[$75] Reply option is not available 

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#425] opened 2021-02-22 09:14 UTC
**Steps**
Go to any roundtable or challenge forum comment
Click on ellipsis

Reply option is not available 

![image](https://user-images.githubusercontent.com/4592712/108687134-55908200-751c-11eb-9342-241319867c47.png)

**Comment by jmgasper** [comment] 2021-02-22 09:47
Challenge https://www.topcoder.com/challenges/871248f5-5a80-44f0-a363-9ec979abb843 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2021-02-22 09:47
Challenge https://www.topcoder.com/challenges/871248f5-5a80-44f0-a363-9ec979abb843 has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by sdgun** [comment] 2021-02-22 10:32
I also notice in production this is all the options I see on challenge discussions: 

![image](https://user-images.githubusercontent.com/4592712/108696195-3cd99980-7527-11eb-89f8-c50416606268.png)

But in Dev I see all below:

![image](https://user-images.githubusercontent.com/4592712/108696240-4a8f1f00-7527-11eb-87e7-d17dd1802b00.png)

**Comment by rootelement** [comment] 2021-02-22 15:03
@atelomycterus are you available? not sure what the problem is here?

**Comment by atelomycterus** [comment] 2021-02-22 15:09
@rootelement I'll have look at it in 5-10 mins. I am working on #422  (user can't see some challenge discussions), 
I've already figured out what happened.

**Comment by rootelement** [comment] 2021-02-22 15:09
Ok, please tag me on any commits so we can push to prod. These are blocking in prod

**Comment by atelomycterus** [comment] 2021-02-22 15:10
@rootelement Ok

**Comment by lakshmiathreya** [comment] 2021-02-22 15:14
@rootelement - there is no time for QA - would rely on your review for the direct Prod push ...

**Comment by atelomycterus** [comment] 2021-02-22 15:27
@rootelement  no changes in code, need to configure permissions.

1. `Reply` is missing. Need to check/configure permissions in PROD:
![image](https://user-images.githubusercontent.com/10196632/108728800-f1c98180-753a-11eb-9321-61a6fd33d429.png)

2.Need check/configure permissions in PROD.

**Comment by rootelement** [comment] 2021-02-22 15:28
I'm sorry i don't understand, you need me to check permissions in prod? Where?

**Comment by atelomycterus** [comment] 2021-02-22 15:33
@rootelement Unfortunately, I don't have permissions to configure it in PROD. @jmgasper configured some permissions today in PROD.
I'm checking permissions for Copilot roles in DEV.

**Comment by rootelement** [comment] 2021-02-22 15:36
What is your username in prod? I'll grant temporary access so you can help us fix this P0

**Comment by atelomycterus** [comment] 2021-02-22 15:37
@rootelement  use  `obog`

**Comment by rootelement** [comment] 2021-02-22 15:37
I've added you as Vanilla Admin in prod @atelomycterus

**Comment by atelomycterus** [comment] 2021-02-22 15:38
@rootelement I have access now. Thanks!

**Comment by sushilshinde** [comment] 2021-02-22 15:42
@rootelement can you also add me, send me admin url

**Comment by atelomycterus** [comment] 2021-02-22 15:45
@rootelement  The permissions for PROD are configured differently than for the DEV. I am reviewing all permissions.

**Comment by rootelement** [comment] 2021-02-22 15:46
@sushilshinde you should have it. it's based on Topcoder roles for tc users. Go to discussions.topcoder.com, click your avatar in the top right corner, and you should see Dashboard.

**Comment by atelomycterus** [comment] 2021-02-22 15:50
@rootelement I've fixed `copilot` and `Connect Copilot` roles.  I am checking  why 'Reply' button is missing

**Comment by atelomycterus** [comment] 2021-02-22 16:00
@rootelement 'Reply' button is also missing in DEV. I'll debug it in DEV. This is not critical because user can post comments.  
You can revoke admin permissions.

**Comment by rootelement** [comment] 2021-02-22 16:03
i'll leave until the reply button is fixed just in case. But thank you

**Comment by atelomycterus** [comment] 2021-02-22 16:45
@rootelement Fixed displaying Reply. PR - https://github.com/topcoder-platform/forums-plugins/pull/62.

### Testing
if user has Comment.Add permission  for a category then 'Reply' should be displayed:
![image](https://user-images.githubusercontent.com/10196632/108739968-373f7c00-7546-11eb-9a16-e5bb6dff29c3.png)

**Comment by atelomycterus** [comment] 2021-02-22 16:52
@jmgasper Summary:
1.   I've fixed copilot and Connect Copilot roles (https://github.com/topcoder-platform/forums/issues/425#issuecomment-783471475) for 'Challenge discussions' category in PROD.  
2.  'Reply' button is missing => Please apply PR ☝️

**Comment by rootelement** [comment] 2021-02-22 17:33
I see this in prod. @sushilshinde and @sdgun please retest
![Screen Shot 2021-02-22 at 12 33 15 PM](https://user-images.githubusercontent.com/5400156/108746352-3852b800-750a-11eb-98ba-b09ccec9089e.png)

**Comment by jmgasper** [comment] 2021-02-22 20:54
Payment task has been updated: https://www.topcoder.com/challenges/871248f5-5a80-44f0-a363-9ec979abb843
*Payments Complete*
Winner: obog
Copilot: ghostar
Challenge `871248f5-5a80-44f0-a363-9ec979abb843` has been paid and closed.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2021-02-22 20:54 UTC
Labels: Dev env, P0, Prod Env, bug, tcx_Assigned, tcx_FixAccepted, tcx_ReadyForReview

**Comment by sdgun** [comment] 2021-02-23 01:43
Verified in production in both roundtables and challenge forums from copilot user and normal user. Reply is available and working as expected. The other missing options for the copilot are also available now.

Copilot:

![image](https://user-images.githubusercontent.com/4592712/108792042-671e6c00-75a6-11eb-8b82-65172cec55bc.png)

![image](https://user-images.githubusercontent.com/4592712/108792071-756c8800-75a6-11eb-894c-59a812042ba8.png)

Normal user:

![image](https://user-images.githubusercontent.com/4592712/108792166-a77dea00-75a6-11eb-9326-bd6cb369e833.png)

**Comment by sdgun** [comment] 2021-02-23 01:49
@jmgasper FYI Reply is not available for comments for all users in Dev, also delete discussion not available for the copilot in Dev

No reply:
![image](https://user-images.githubusercontent.com/4592712/108792361-16f3d980-75a7-11eb-9aab-c6e67e856918.png)

No delete:
![image](https://user-images.githubusercontent.com/4592712/108792491-676b3700-75a7-11eb-8d2d-e22ed4e2b2a4.png)

**Comment by jmgasper** [comment] 2021-02-23 02:30
@sdgun - Fixed in dev.  Copilots should only be able to announce or move - not edit or delete other member's comments.

**Comment by sdgun** [comment] 2021-02-23 03:38
@jmgasper Copilot sees the Edit on challenges, but when tries to do a change and Save, see the below:


https://user-images.githubusercontent.com/4592712/108799334-14e54700-75b6-11eb-93b1-c8fb5e5558a8.mp4

**Comment by sdgun** [comment] 2021-02-23 03:47
@jmgasper One more thing, these options we can only see through Home >> CHALLENGE DISCUSSIONS. When access the challenges from Roundtables >> CHALLENGE DISCUSSIONS, the ellipsis is not available.

Uploading Screencast 2021-02-23.mp4…

**Comment by jmgasper** [comment] 2021-02-23 03:59
@sdgun - Yes, that's acceptable.  Copilots have more permissions on challenge discussions than in the roundtables.
