### ISSUE TITLE
[$70] Getting Exception while creating new discussion without logging in

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/forums#108] opened 2020-11-05 06:40 UTC
Description:
Getting Exception while creating new discussion without logging in

Screenshot:

![image (13)](https://user-images.githubusercontent.com/55895538/98206394-2827c480-1f7d-11eb-803b-862d6f1946d6.png)

**Comment by jmgasper** [comment] 2020-11-05 09:50
@atelomycterus - Another permission issue - is there a good way to block users from this `New Discussion` page if they aren't logged in?

**Comment by jmgasper** [comment] 2020-11-05 09:50
Contest https://www.topcoder.com/challenges/30149001 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-05 13:15
Contest https://www.topcoder.com/challenges/30149001 has been updated - obog has been unassigned.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-05 21:24
Contest https://www.topcoder.com/challenges/30149001 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment] 2020-11-06 21:12
@jmgasper Couldn't reproduce it my local env but I see it on vanilla.topcoder-dev.com. The button shouldn't be displayed for Guest. Vaniila code looks ok.  It looks like the session is still existing after sign out. I've added logging, so I'll take a look at it after deploying. 

Also I noticed yesterday the same issues https://github.com/topcoder-platform/forums/issues/107.   
No errors in `cw -p topcoder-dev -r us-east-1 tail -f /aws/ecs/tc-forums:DEV/vanilla-forums -b1d`
Could you ask Topcoder admins if there was any kind of testing? 

PR -https://github.com/topcoder-platform/forums-plugins/pull/37

**Comment by atelomycterus** [comment] 2020-11-10 12:10
Guests has more permissions.
![image](https://user-images.githubusercontent.com/10196632/98671473-5fbfb380-2365-11eb-9fb9-362268d0eb5b.png)

Permissions  for guests from Rest API and UI - correct. 
TODO: it looks like an issue in Vanilla UserModel loadPermissions. I'll fix it.

https://vanilla.topcoder-dev.com/api/v2/roles/2?expand=all:
```
{
  "roleID": 2,
  "name": "Guest",
  "description": "Guests can only view content. Anyone browsing the site who is not signed in is considered to be a \"Guest\".",
  "type": "guest",
  "deletable": false,
  "canSession": false,
  "personalInfo": false,
  "permissions": [
    {
      "type": "global",
      "permissions": {
        "advancedNotifications.allow": false,
        "applicants.manage": false,
        "category.manage": false,
        "community.manage": false,
        "community.moderate": false,
        "conversations.add": false,
        "conversations.moderate": false,
        "debugger.view": true,
        "email.view": false,
        "emailInvitations.add": false,
        "groups.add": false,
        "groups.moderate": false,
        "personalInfo.view": false,
        "profiles.edit": false,
        "profiles.view": true,
        "settings.view": false,
        "site.manage": false,
        "tags.add": false,
        "tokens.add": false,
        "uploads.add": false,
        "users.add": false,
        "users.delete": false,
        "users.edit": false
      }
    },
    {
      "id": 0,
      "type": "category",
      "permissions": {
        "comments.add": false,
        "comments.delete": false,
        "comments.edit": false,
        "discussions.add": false,
        "discussions.manage": false,
        "discussions.moderate": false,
        "discussions.view": false
      }
    }
  ]
}
```

**Comment by atelomycterus** [comment] 2020-11-21 16:35
@jmgasper Please apply PRs: https://github.com/topcoder-platform/forums-plugins/pull/47 ,
https://github.com/topcoder-platform/forums/pull/221

I'll test it in the dev because I can't reproduce it  in my local env. If it's fixed, I'll change the ticket status.

**Comment by atelomycterus** [comment] 2020-11-22 12:41
@jmgasper Keep you updated it:

Please apply PR- https://github.com/topcoder-platform/forums/pull/223
https://github.com/topcoder-platform/forums-plugins/pull/48

Thanks!

 UserModel.loadPermissions loads a list of permissions from cache. UserID=0 is reserved for Guest in Vanilla. If the cache is enabled, Vanilla caches 'User.0'/'User.0.permissions/User.0.roles' once and don't clear it.

I've tried to check the keys for Guest in memcached but the server is not accessible using telnet.   
I get access denied using aws cli with the topcoder profile.

The original Vanilla method 'clearCache' doesn't clear cached data for UserID = 0. 
```
  /**
     * Delete cached data for user.
     *
     * @param int|null $userID The user to clear the cache for.
     * @return bool Returns **true** if the cache was cleared or **false** otherwise.
     */
    public function clearCache($userID, $cacheTypesToClear = null) {
        if (is_null($userID) || !$userID) {
            return false;
        }
      
...
}
```

So let's check after deploying. Fixed the original method.  Added  the next lines to clear cached data for Guest in topcoder plugin
```
        $userModel = new UserModel();
        self::log('Guest permissions:', ['IsCacheEnabled:' => Gdn::cache()->activeEnabled() , 'Permissions' => $userModel->getPermissions(0)]);
        // Delete cached data for userID=0 .
        $cacheCleared = $userModel->clearCache(0);
        self::log('After clearing cache for Guest:', ['IsCacheCleared' => $cacheCleared,  'Permissions' => $userModel->getPermissions(0)]);

```

**Comment by jmgasper** [comment] 2020-11-22 23:42
@atelomycterus - I deployed and still see the issue.  Can we hide `New Discussion` for users not logged in?

**Comment by atelomycterus** [comment] 2020-11-23 06:07
@jmgasper I see. It's displayed due to 'Discussion.Add' permission.  I'll hide it. 
I've added an user with Guest role in the dev, the permissions are loaded correctly.
Could you create a dump of DB from the dev? I'll debug it locally. The same issue exists in the prod.

**Comment by jmgasper** [comment] 2020-11-23 22:33
@atelomycterus - I've asked for a DB dump.  Still waiting on that.

**Comment by atelomycterus** [comment] 2020-11-24 12:07
@jmgasper Thanks! Without the dump, it would be impossible to understand what the problem was.

PRs: https://github.com/topcoder-platform/forums/pull/233
https://github.com/topcoder-platform/forums-plugins/pull/49

### Issue
There were 2 records with UserID=0 in UserRole. There are no user with UserID=0 in User table.  After removing these records, everything works as expected. 
![image](https://user-images.githubusercontent.com/10196632/100083410-80eecc80-2e5a-11eb-8960-2d7f83ea8514.png)

So the records with UserID = 0 will be deleted after deploying. Guest should have guest permissions.  
Issue: saveRoles() didn't validate UserID. It was possible to add records with UserID=0.
Fix: Roles should be saved if UserID >0.

**Comment by jmgasper** [comment] 2020-11-24 22:02
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30149001<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2020-11-24 22:02 UTC
Labels: Dev env, P4, bug, tcx_Assigned, tcx_FixAccepted

**Comment by sdgun** [comment] 2020-11-25 04:20
Verified, the New Discussion button is not available before logging in.
